import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/alerts/vercel/create.ts',
    unsubscribe: 'src/alerts/vercel/unsubscribe.ts',
  },
  format: ['esm'],
  outDir: 'api/alerts',
  target: 'node18',
  platform: 'node',
  minify: false,
  sourcemap: false,
  clean: true,
  dts: false,
  splitting: false,
  banner: {
    js: '// Generated by tsup from src/alerts — do not edit by hand.\n',
  },
  outExtension() {
    return { js: '.js' };
  },
});
