import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/route-validator/vercel/index.ts',
  },
  format: ['esm'],
  outDir: 'api/route-validator',
  target: 'node18',
  platform: 'node',
  minify: false,
  sourcemap: false,
  clean: true,
  dts: false,
  splitting: false,
  banner: {
    js: '// Generated by tsup from src/route-validator — do not edit by hand.\n',
  },
  outExtension() {
    return { js: '.js' };
  },
});
