// Generated by tsup from src/market-data — do not edit by hand.


// src/alerts/rate-limit.ts
var buckets = /* @__PURE__ */ new Map();
function checkRateLimit(key, limit = 10, windowMs = 60 * 60 * 1e3, now = Date.now()) {
  const existing = buckets.get(key);
  if (!existing || now >= existing.resetAt) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { allowed: true, retryAfterSec: 0 };
  }
  if (existing.count >= limit) {
    return {
      allowed: false,
      retryAfterSec: Math.max(1, Math.ceil((existing.resetAt - now) / 1e3))
    };
  }
  existing.count += 1;
  return { allowed: true, retryAfterSec: 0 };
}

// src/market-data/allowlist.ts
var MARKET_DATA_EXCHANGES = [
  "Binance",
  "MEXC",
  "Bybit",
  "OKX",
  "KuCoin",
  "Gate"
];
var MARKET_DATA_ASSETS = [
  "BTC",
  "ETH",
  "SOL",
  "XRP",
  "TON",
  "DOGE",
  "ADA",
  "BNB",
  "TRX",
  "DOT",
  "LINK",
  "LTC",
  "AVAX",
  "MATIC",
  "SHIB",
  "UNI",
  "XLM",
  "NEAR",
  "ATOM",
  "APT"
];
var MARKET_DATA_QUOTE = "USDT";
var MARKET_DATA_OPERATIONS = ["spread_snapshot", "reference_price"];
var HOMEPAGE_SYMBOLS = MARKET_DATA_ASSETS.map(
  (a) => `${a}${MARKET_DATA_QUOTE}`
);
var EXCHANGE_SET = new Set(MARKET_DATA_EXCHANGES);
var ASSET_SET = new Set(MARKET_DATA_ASSETS);
var EXCHANGE_ALIASES = {
  binance: "Binance",
  bybit: "Bybit",
  mexc: "MEXC",
  okx: "OKX",
  kucoin: "KuCoin",
  gate: "Gate",
  "gate.io": "Gate",
  gateio: "Gate"
};
function normalizeMarketExchange(raw) {
  if (typeof raw !== "string") return null;
  const t = raw.trim();
  if (EXCHANGE_SET.has(t)) return t;
  return EXCHANGE_ALIASES[t.toLowerCase()] ?? null;
}
function normalizeMarketAsset(raw) {
  if (typeof raw !== "string") return null;
  let s = raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!s) return null;
  if (s.endsWith("USDT") && s.length > 4) s = s.slice(0, -4);
  if (ASSET_SET.has(s)) return s;
  return null;
}
function toSpotSymbol(asset) {
  return `${asset}${MARKET_DATA_QUOTE}`;
}
var SPREAD_SNAPSHOT_TTL_MS = 1e4;
var REFERENCE_PRICE_TTL_MS = 8e3;
var ERROR_CACHE_TTL_MS = 2e3;
var MAX_QUERY_LENGTH = 512;
var FETCH_CONCURRENCY = 3;

// src/route-validator/cache.ts
var store = /* @__PURE__ */ new Map();
function cacheGet(key, now = Date.now()) {
  const hit = store.get(key);
  if (!hit) return null;
  if (now >= hit.expiresAt) {
    store.delete(key);
    return null;
  }
  return hit.value;
}
function cacheSet(key, value, ttlMs, now = Date.now()) {
  store.set(key, { value, expiresAt: now + ttlMs });
  if (store.size > 200) {
    for (const [k, v] of store) {
      if (now >= v.expiresAt) store.delete(k);
    }
  }
}

// src/market-data/concurrency.ts
async function mapPool(items, concurrency, fn) {
  const limit = Math.max(1, concurrency);
  const results = new Array(items.length);
  let next = 0;
  async function worker() {
    while (next < items.length) {
      const i = next++;
      results[i] = await fn(items[i], i);
    }
  }
  const workers = Array.from({ length: Math.min(limit, items.length) }, () => worker());
  await Promise.all(workers);
  return results;
}

// src/market-data/spread.ts
function computeSpreadPayloadFromExchangePrices(exchangeSnapshots, targetSymbols, opts = {}) {
  const exchanges = Object.keys(exchangeSnapshots || {});
  const symbolsData = {};
  const errors = {};
  for (const symbol of targetSymbols) {
    const prices = {};
    const symErrors = {};
    for (const ex of exchanges) {
      const priceMap = exchangeSnapshots[ex] || {};
      const v = priceMap[symbol];
      if (typeof v === "number" && Number.isFinite(v) && v > 0) {
        prices[ex] = v;
      } else {
        symErrors[ex] = "no_live_price";
      }
    }
    let best_buy = null;
    let best_sell = null;
    let absolute_diff = null;
    let spread_percent = null;
    const values = Object.values(prices);
    if (values.length > 0) {
      const minPrice = Math.min(...values);
      const maxPrice = Math.max(...values);
      const bestBuyEx = Object.keys(prices).find((k) => prices[k] === minPrice) || null;
      const bestSellEx = Object.keys(prices).find((k) => prices[k] === maxPrice) || null;
      if (bestBuyEx && bestSellEx) {
        best_buy = { exchange: bestBuyEx, price: minPrice };
        best_sell = { exchange: bestSellEx, price: maxPrice };
        absolute_diff = +(maxPrice - minPrice).toFixed(2);
        spread_percent = minPrice > 0 ? +((maxPrice - minPrice) / minPrice).toFixed(8) : null;
      }
    }
    symbolsData[symbol] = {
      prices,
      absolute_diff,
      spread_percent,
      best_buy,
      best_sell,
      binance_price: prices.Binance ?? null,
      bybit_price: prices.Bybit ?? null
    };
    if (Object.keys(symErrors).length) errors[symbol] = symErrors;
  }
  const now = (opts.now ?? (() => /* @__PURE__ */ new Date()))();
  return {
    timestamp: now.toISOString(),
    symbols: symbolsData,
    errors,
    exchanges,
    source: "live_gateway",
    warnings: opts.warnings ?? [],
    unavailable_exchanges: opts.unavailableExchanges ?? []
  };
}

// src/route-validator/symbols.ts
var VALIDATOR_EXCHANGES = ["Binance", "Bybit", "MEXC"];
var VALIDATOR_ASSETS = ["BTC", "ETH", "SOL", "XRP"];
var EXCHANGE_SET2 = new Set(VALIDATOR_EXCHANGES);
var ASSET_SET2 = new Set(VALIDATOR_ASSETS);
var UPSTREAM_TIMEOUT_MS = 6e3;

// src/route-validator/adapters/base.ts
var UpstreamError = class extends Error {
  constructor(message, category) {
    super(message);
    this.category = category;
    this.name = "UpstreamError";
  }
};
var DEFAULT_HEADERS = {
  Accept: "application/json",
  // Some exchanges block blank / serverless default UAs.
  "User-Agent": "CoinNavigator/1.0 (+https://coinnavigator.net)"
};
async function fetchJson(url, opts = {}) {
  const timeoutMs = opts.timeoutMs ?? UPSTREAM_TIMEOUT_MS;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      method: "GET",
      headers: {
        ...DEFAULT_HEADERS,
        ...opts.headers ?? {}
      },
      signal: controller.signal
    });
    if (res.status === 429) {
      throw new UpstreamError("rate_limited", "rate_limit");
    }
    if (!res.ok) {
      throw new UpstreamError(`http_${res.status}`, "http");
    }
    return await res.json();
  } catch (err) {
    if (err instanceof UpstreamError) throw err;
    if (err instanceof Error && err.name === "AbortError") {
      throw new UpstreamError("timeout", "timeout");
    }
    throw new UpstreamError("unavailable", "unavailable");
  } finally {
    clearTimeout(timer);
  }
}
async function fetchJsonWithFallbacks(urls, opts = {}) {
  if (!urls.length) throw new UpstreamError("no_urls", "unavailable");
  let last = null;
  for (const url of urls) {
    try {
      return await fetchJson(url, opts);
    } catch (err) {
      if (err instanceof UpstreamError) {
        last = err;
        continue;
      }
      last = new UpstreamError("unavailable", "unavailable");
    }
  }
  throw last ?? new UpstreamError("unavailable", "unavailable");
}

// src/route-validator/adapters/hosts.ts
var BINANCE_API_HOSTS = [
  "https://api.binance.com",
  "https://data-api.binance.vision"
];
var BYBIT_API_HOSTS = [
  "https://api.bybit.com",
  "https://api.bytick.com"
];

// src/market-data/tickers.ts
function filterMap(symbols, rows) {
  const map = {};
  for (const row of rows) {
    if (!symbols.has(row.symbol)) continue;
    if (!Number.isFinite(row.price) || row.price <= 0) continue;
    map[row.symbol] = row.price;
  }
  return map;
}
function parseBinanceTickerArray(json) {
  if (!Array.isArray(json)) throw new UpstreamError("malformed", "malformed");
  const rows = [];
  for (const row of json) {
    if (!row || typeof row !== "object") continue;
    const r = row;
    if (typeof r.symbol !== "string") continue;
    rows.push({ symbol: r.symbol, price: parseFloat(String(r.price)) });
  }
  return rows;
}
async function fetchBinanceTickers(symbols) {
  const json = await fetchJsonWithFallbacks(
    BINANCE_API_HOSTS.map((h) => `${h}/api/v3/ticker/price`)
  );
  return filterMap(symbols, parseBinanceTickerArray(json));
}
async function fetchMexcTickers(symbols) {
  const json = await fetchJson("https://api.mexc.com/api/v3/ticker/price");
  return filterMap(symbols, parseBinanceTickerArray(json));
}
async function fetchBybitTickers(symbols) {
  const json = await fetchJsonWithFallbacks(
    BYBIT_API_HOSTS.map((h) => `${h}/v5/market/tickers?category=spot`)
  );
  if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
  const body = json;
  const list = Array.isArray(body.result?.list) ? body.result.list : [];
  const rows = [];
  for (const row of list) {
    if (!row || typeof row !== "object") continue;
    const r = row;
    if (typeof r.symbol !== "string") continue;
    rows.push({ symbol: r.symbol, price: parseFloat(String(r.lastPrice)) });
  }
  return filterMap(symbols, rows);
}
async function fetchOkxTickers(symbols) {
  const json = await fetchJson("https://www.okx.com/api/v5/market/tickers?instType=SPOT");
  if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
  const body = json;
  const list = Array.isArray(body.data) ? body.data : [];
  const rows = [];
  for (const row of list) {
    if (!row || typeof row !== "object") continue;
    const r = row;
    if (typeof r.instId !== "string" || !r.instId.endsWith("-USDT")) continue;
    const symbol = r.instId.replace("-", "");
    rows.push({ symbol, price: parseFloat(String(r.last)) });
  }
  return filterMap(symbols, rows);
}
async function fetchKucoinTickers(symbols) {
  const json = await fetchJson("https://api.kucoin.com/api/v1/market/allTickers");
  if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
  const body = json;
  const list = Array.isArray(body.data?.ticker) ? body.data.ticker : [];
  const rows = [];
  for (const row of list) {
    if (!row || typeof row !== "object") continue;
    const r = row;
    if (typeof r.symbol !== "string" || !r.symbol.endsWith("-USDT")) continue;
    const symbol = r.symbol.replace("-", "");
    rows.push({ symbol, price: parseFloat(String(r.last)) });
  }
  return filterMap(symbols, rows);
}
async function fetchGateTickers(symbols) {
  const json = await fetchJson("https://api.gateio.ws/api/v4/spot/tickers");
  if (!Array.isArray(json)) throw new UpstreamError("malformed", "malformed");
  const rows = [];
  for (const row of json) {
    if (!row || typeof row !== "object") continue;
    const r = row;
    if (typeof r.currency_pair !== "string" || !r.currency_pair.endsWith("_USDT")) continue;
    const symbol = r.currency_pair.replace("_", "");
    rows.push({ symbol, price: parseFloat(String(r.last)) });
  }
  return filterMap(symbols, rows);
}
async function fetchBinanceReferencePrice(symbol) {
  const json = await fetchJsonWithFallbacks(
    BINANCE_API_HOSTS.map(
      (h) => `${h}/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`
    )
  );
  if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
  const body = json;
  const p = parseFloat(String(body.price));
  if (!Number.isFinite(p) || p <= 0) throw new UpstreamError("malformed_price", "malformed");
  return p;
}
async function fetchMexcReferencePrice(symbol) {
  const json = await fetchJson(
    `https://api.mexc.com/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`
  );
  if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
  const body = json;
  const p = parseFloat(String(body.price));
  if (!Number.isFinite(p) || p <= 0) throw new UpstreamError("malformed_price", "malformed");
  return p;
}

// src/market-data/tickers-index.ts
var TICKER_FETCHERS = {
  Binance: fetchBinanceTickers,
  MEXC: fetchMexcTickers,
  Bybit: fetchBybitTickers,
  OKX: fetchOkxTickers,
  KuCoin: fetchKucoinTickers,
  Gate: fetchGateTickers
};

// src/market-data/service.ts
async function fetchOneExchange(exchange, symbols) {
  try {
    const prices = await TICKER_FETCHERS[exchange](symbols);
    if (!prices || Object.keys(prices).length === 0) {
      return { exchange, prices: null, reason: "empty" };
    }
    return { exchange, prices };
  } catch (err) {
    const reason = err instanceof UpstreamError ? err.category : "unavailable";
    return { exchange, prices: null, reason };
  }
}
async function buildSpreadSnapshot(opts = {}) {
  const cacheKey = "op=spread_snapshot";
  if (!opts.skipCache) {
    const hit = cacheGet(cacheKey);
    if (hit) {
      return { ok: true, data: hit, warnings: hit.warnings ?? [], cacheHit: true };
    }
  }
  const symbolSet = new Set(HOMEPAGE_SYMBOLS);
  const settled = await mapPool(
    MARKET_DATA_EXCHANGES,
    FETCH_CONCURRENCY,
    (ex) => fetchOneExchange(ex, symbolSet)
  );
  const snapshots = {};
  const unavailable = [];
  const warnings = [];
  for (const row of settled) {
    if (row.prices) {
      snapshots[row.exchange] = row.prices;
    } else {
      unavailable.push(row.exchange);
      warnings.push(`${row.exchange} unavailable (${row.reason || "error"})`);
    }
  }
  if (Object.keys(snapshots).length < 2) {
    cacheSet(cacheKey + ":fail", { failed: true }, ERROR_CACHE_TTL_MS);
    return { ok: false, category: "unavailable", reason: "insufficient_exchanges" };
  }
  const payload = computeSpreadPayloadFromExchangePrices(snapshots, HOMEPAGE_SYMBOLS, {
    unavailableExchanges: unavailable,
    warnings,
    ...opts.now ? { now: opts.now } : {}
  });
  cacheSet(cacheKey, payload, SPREAD_SNAPSHOT_TTL_MS);
  return { ok: true, data: payload, warnings, cacheHit: false };
}
async function buildReferencePrice(raw, opts = {}) {
  const asset = normalizeMarketAsset(raw.asset);
  if (!asset) return { ok: false, category: "unsupported", reason: "unsupported_asset" };
  const quote = typeof raw.quote === "string" && raw.quote.trim() ? raw.quote.trim().toUpperCase() : "USDT";
  if (quote !== "USDT") return { ok: false, category: "unsupported", reason: "unsupported_quote" };
  const requested = normalizeMarketExchange(raw.exchange ?? "Binance");
  if (!requested) return { ok: false, category: "unsupported", reason: "unsupported_exchange" };
  if (requested !== "Binance" && requested !== "MEXC") {
    return { ok: false, category: "unsupported", reason: "reference_exchange_unsupported" };
  }
  const symbol = toSpotSymbol(asset);
  const cacheKey = `op=reference_price&ex=${requested}&sym=${symbol}`;
  if (!opts.skipCache) {
    const hit = cacheGet(cacheKey);
    if (hit) return { ok: true, data: hit, warnings: [], cacheHit: true };
  }
  const warnings = [];
  let price = null;
  let usedExchange = requested === "MEXC" ? "MEXC" : "Binance";
  if (requested === "Binance") {
    try {
      price = await fetchBinanceReferencePrice(symbol);
      usedExchange = "Binance";
    } catch {
      try {
        price = await fetchMexcReferencePrice(symbol);
        usedExchange = "MEXC";
        warnings.push(
          "Binance reference price unavailable from this runtime; used MEXC public ticker instead."
        );
      } catch {
        price = null;
      }
    }
  } else {
    try {
      price = await fetchMexcReferencePrice(symbol);
      usedExchange = "MEXC";
    } catch {
      price = null;
    }
  }
  if (price == null) {
    cacheSet(cacheKey + ":fail", { failed: true }, ERROR_CACHE_TTL_MS);
    return { ok: false, category: "unavailable", reason: "upstream_failed" };
  }
  const data = {
    asset,
    quote: "USDT",
    exchange: usedExchange,
    price,
    fetched_at: (/* @__PURE__ */ new Date()).toISOString(),
    source: "live_gateway"
  };
  cacheSet(cacheKey, data, REFERENCE_PRICE_TTL_MS);
  return { ok: true, data, warnings, cacheHit: false };
}

// src/market-data/http.ts
function header(req, name) {
  const raw = req.headers?.[name] ?? req.headers?.[name.toLowerCase()];
  if (Array.isArray(raw)) return raw[0] || "";
  return typeof raw === "string" ? raw : "";
}
function clientIp(req) {
  const fwd = header(req, "x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim().slice(0, 64);
  return (req.socket?.remoteAddress || "unknown").slice(0, 64);
}
function readQuery(req) {
  if (req.query && typeof req.query === "object") {
    const sp = new URLSearchParams();
    for (const [k, v] of Object.entries(req.query)) {
      if (v == null) continue;
      sp.set(k, Array.isArray(v) ? String(v[0] ?? "") : String(v));
    }
    return sp;
  }
  try {
    const u = new URL(req.url || "/", "http://localhost");
    return u.searchParams;
  } catch {
    return new URLSearchParams();
  }
}
function firstParam(sp, key) {
  const v = sp.get(key);
  return v == null || v === "" ? null : v;
}
async function handleMarketDataRequest(req, res) {
  res.setHeader("Cache-Control", "public, max-age=5, s-maxage=5, stale-while-revalidate=10");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  if (req.method === "OPTIONS") {
    res.setHeader("Allow", "GET, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "GET") {
    res.status(405).json({
      ok: false,
      error: { code: "METHOD_NOT_ALLOWED", message: "Please use GET with a supported operation." }
    });
    return;
  }
  const rawUrl = req.url || "";
  if (rawUrl.length > MAX_QUERY_LENGTH) {
    res.status(400).json({
      ok: false,
      error: { code: "VALIDATION_ERROR", message: "Invalid request." }
    });
    return;
  }
  const ip = clientIp(req);
  const rl = checkRateLimit(`market-data:${ip}`, 60, 6e4);
  if (!rl.allowed) {
    res.setHeader("Retry-After", String(rl.retryAfterSec));
    res.status(429).json({
      ok: false,
      error: { code: "RATE_LIMITED", message: "Too many requests. Please try again later." }
    });
    return;
  }
  const sp = readQuery(req);
  const operation = firstParam(sp, "operation");
  if (!operation || !MARKET_DATA_OPERATIONS.includes(operation)) {
    res.status(400).json({
      ok: false,
      error: { code: "VALIDATION_ERROR", message: "Unsupported or missing operation." }
    });
    return;
  }
  for (const banned of ["url", "path", "endpoint", "proxy", "target", "host"]) {
    if (sp.has(banned)) {
      res.status(400).json({
        ok: false,
        error: { code: "VALIDATION_ERROR", message: "Invalid request." }
      });
      return;
    }
  }
  try {
    if (operation === "spread_snapshot") {
      const out2 = await buildSpreadSnapshot();
      if (!out2.ok) {
        res.status(503).json({
          ok: false,
          error: {
            code: "MARKET_DATA_UNAVAILABLE",
            message: "Live market data is temporarily unavailable."
          }
        });
        return;
      }
      res.status(200).json({
        ok: true,
        data: out2.data,
        warnings: out2.warnings,
        cache_hit: out2.cacheHit
      });
      return;
    }
    const out = await buildReferencePrice({
      asset: firstParam(sp, "asset") ?? "BTC",
      quote: firstParam(sp, "quote") ?? "USDT",
      exchange: firstParam(sp, "exchange") ?? "Binance"
    });
    if (!out.ok) {
      if (out.category === "unsupported" || out.category === "validation") {
        res.status(400).json({
          ok: false,
          error: { code: "VALIDATION_ERROR", message: "Please check asset, quote and exchange." }
        });
        return;
      }
      res.status(503).json({
        ok: false,
        error: {
          code: "MARKET_DATA_UNAVAILABLE",
          message: "Live market data is temporarily unavailable."
        }
      });
      return;
    }
    res.status(200).json({
      ok: true,
      data: out.data,
      warnings: out.warnings,
      cache_hit: out.cacheHit
    });
  } catch {
    res.status(500).json({
      ok: false,
      error: {
        code: "SERVER_ERROR",
        message: "Live market data is temporarily unavailable."
      }
    });
  }
}

// src/market-data/vercel/index.ts
async function handler(req, res) {
  await handleMarketDataRequest(req, res);
}
export {
  handler as default
};
