// Generated by tsup from src/alerts — do not edit by hand.


// src/alerts/rate-limit.ts
var buckets = /* @__PURE__ */ new Map();
function checkRateLimit(key, limit = 10, windowMs = 60 * 60 * 1e3, now = Date.now()) {
  const existing = buckets.get(key);
  if (!existing || now >= existing.resetAt) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { allowed: true, retryAfterSec: 0 };
  }
  if (existing.count >= limit) {
    return {
      allowed: false,
      retryAfterSec: Math.max(1, Math.ceil((existing.resetAt - now) / 1e3))
    };
  }
  existing.count += 1;
  return { allowed: true, retryAfterSec: 0 };
}

// src/alerts/email.ts
var ResendEmailAdapter = class _ResendEmailAdapter {
  constructor(apiKey, fromAddress) {
    this.apiKey = apiKey;
    this.fromAddress = fromAddress;
  }
  static fromEnv(env = process.env) {
    const apiKey = (env.RESEND_API_KEY || "").trim();
    if (!apiKey) return null;
    const fromAddress = (env.ALERTS_FROM_EMAIL || "CoinNavigator <alerts@coinnavigator.net>").trim();
    return new _ResendEmailAdapter(apiKey, fromAddress);
  }
  isEnabled() {
    return Boolean(this.apiKey);
  }
  async sendAlertConfirmation(payload) {
    if (!this.isEnabled()) return "disabled";
    try {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          from: this.fromAddress,
          to: [payload.to],
          subject: "CoinNavigator alert subscription confirmed",
          text: [
            `Your CoinNavigator opportunity alert for ${payload.asset} (${payload.alertScope}) is active.`,
            "",
            "Alerts are estimates, not financial advice. Market conditions may change before execution.",
            "",
            `Unsubscribe: ${payload.unsubscribeUrl}`
          ].join("\n")
        })
      });
      if (!res.ok) return "failed";
      return "queued";
    } catch {
      return "failed";
    }
  }
};
var NoopEmailAdapter = class {
  isEnabled() {
    return false;
  }
  async sendAlertConfirmation() {
    return "disabled";
  }
};
function getEmailAdapter(env = process.env) {
  return ResendEmailAdapter.fromEnv(env) ?? new NoopEmailAdapter();
}

// src/alerts/storage.ts
var StorageConfigError = class extends Error {
  constructor(message = "Alert storage is not configured") {
    super(message);
    this.name = "StorageConfigError";
  }
};
var StorageFailureError = class extends Error {
  constructor(message = "Alert storage failed") {
    super(message);
    this.name = "StorageFailureError";
  }
};

// src/alerts/tokens.ts
import { createHash, randomBytes } from "crypto";
function createUnsubscribeToken() {
  return randomBytes(32).toString("hex");
}
function createId() {
  return randomBytes(16).toString("hex");
}
function hashUserAgent(userAgent) {
  if (!userAgent || typeof userAgent !== "string") return null;
  const trimmed = userAgent.trim().slice(0, 512);
  if (!trimmed) return null;
  return createHash("sha256").update(trimmed).digest("hex").slice(0, 32);
}
function normalizeEmail(email) {
  return email.trim().toLowerCase();
}

// src/alerts/allowlist.ts
var SUPPORTED_EXCHANGES = [
  "Binance",
  "MEXC",
  "Bybit",
  "OKX",
  "KuCoin",
  "Gate"
];
var SUPPORTED_ASSETS = [
  "BTC",
  "ETH",
  "SOL",
  "XRP",
  "TON",
  "DOGE",
  "ADA",
  "BNB",
  "TRX",
  "DOT",
  "LINK",
  "LTC",
  "AVAX",
  "MATIC",
  "SHIB",
  "UNI",
  "XLM",
  "NEAR",
  "ATOM",
  "APT"
];
var EXCHANGE_SET = new Set(SUPPORTED_EXCHANGES);
var ASSET_SET = new Set(SUPPORTED_ASSETS);
var EXCHANGE_ALIASES = {
  gate: "Gate",
  "gate.io": "Gate",
  gateio: "Gate",
  binance: "Binance",
  mexc: "MEXC",
  bybit: "Bybit",
  okx: "OKX",
  kucoin: "KuCoin"
};
function normalizeAsset(raw) {
  if (typeof raw !== "string") return null;
  let s = raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!s) return null;
  if (s.endsWith("USDT") && s.length > 4) s = s.slice(0, -4);
  if (ASSET_SET.has(s)) return s;
  return null;
}
function normalizeExchange(raw) {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (EXCHANGE_SET.has(trimmed)) return trimmed;
  const alias = EXCHANGE_ALIASES[trimmed.toLowerCase()];
  return alias ?? null;
}

// src/alerts/types.ts
var CONSENT_VERSION = "alerts-v1-2026-08-04";

// src/alerts/validate.ts
var EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
var MAX_SOURCE_LEN = 120;
var MAX_PCT = 100;
var MAX_USD = 1e6;
function asFiniteNumber(raw) {
  if (raw === null || raw === void 0 || raw === "") return null;
  if (typeof raw === "number") return Number.isFinite(raw) ? raw : null;
  if (typeof raw === "string") {
    const n = Number(raw.trim());
    return Number.isFinite(n) ? n : null;
  }
  return null;
}
function clipSource(raw, fallback) {
  if (typeof raw !== "string" || !raw.trim()) return fallback;
  return raw.trim().slice(0, MAX_SOURCE_LEN);
}
function validateCreateAlertInput(raw) {
  if (!raw || typeof raw !== "object") {
    return { ok: false, reason: "invalid_payload" };
  }
  const body = raw;
  if (typeof body.website === "string" && body.website.trim() !== "") {
    return { ok: false, reason: "honeypot" };
  }
  if (body.consent !== true) {
    return { ok: false, reason: "missing_consent" };
  }
  if (typeof body.email !== "string" || !EMAIL_RE.test(body.email.trim())) {
    return { ok: false, reason: "invalid_email" };
  }
  const email = normalizeEmail(body.email);
  if (email.length > 254) {
    return { ok: false, reason: "invalid_email" };
  }
  const asset = normalizeAsset(body.asset);
  if (!asset) {
    return { ok: false, reason: "unsupported_asset" };
  }
  const scopeRaw = body.alert_scope;
  if (scopeRaw !== "exact_pair" && scopeRaw !== "any_pair") {
    return { ok: false, reason: "invalid_scope" };
  }
  const alert_scope = scopeRaw;
  let buy_exchange = normalizeExchange(body.buy_exchange);
  let sell_exchange = normalizeExchange(body.sell_exchange);
  if (alert_scope === "exact_pair") {
    if (!buy_exchange || !sell_exchange) {
      return { ok: false, reason: "unsupported_exchange" };
    }
    if (buy_exchange === sell_exchange) {
      return { ok: false, reason: "invalid_exchange_pair" };
    }
  } else {
    buy_exchange = null;
    sell_exchange = null;
  }
  const minPct = asFiniteNumber(body.minimum_net_profit_pct);
  if (minPct !== null && (minPct < 0 || minPct > MAX_PCT)) {
    return { ok: false, reason: "invalid_threshold" };
  }
  const minUsd = asFiniteNumber(body.minimum_net_profit_usd);
  if (minUsd !== null && (minUsd < 0 || minUsd > MAX_USD)) {
    return { ok: false, reason: "invalid_threshold" };
  }
  const consent_version = typeof body.consent_version === "string" && body.consent_version.trim() ? body.consent_version.trim().slice(0, 64) : CONSENT_VERSION;
  return {
    ok: true,
    value: {
      email,
      asset,
      buy_exchange,
      sell_exchange,
      alert_scope,
      minimum_net_profit_pct: minPct,
      minimum_net_profit_usd: minUsd,
      source_page: clipSource(body.source_page, "home"),
      source_context: clipSource(body.source_context, "check_real_profit"),
      consent_version,
      user_agent_hash: hashUserAgent(
        typeof body.user_agent === "string" ? body.user_agent : null
      )
    }
  };
}

// src/alerts/service.ts
function genericValidation() {
  return {
    ok: false,
    error: {
      code: "VALIDATION_ERROR",
      message: "Please check the submitted details."
    }
  };
}
async function createAlertSubscription(rawBody, deps) {
  const validated = validateCreateAlertInput(rawBody);
  if (!validated.ok) {
    const category = validated.reason === "honeypot" ? "honeypot" : validated.reason === "missing_consent" ? "missing_consent" : validated.reason === "unsupported_asset" ? "unsupported_asset" : validated.reason === "unsupported_exchange" || validated.reason === "invalid_exchange_pair" ? "unsupported_exchange" : validated.reason === "invalid_email" ? "invalid_email" : "validation";
    return {
      response: genericValidation(),
      httpStatus: 400,
      analytics: { outcome: "failed", failure_category: category }
    };
  }
  const input = validated.value;
  const now = (deps.now ?? (() => (/* @__PURE__ */ new Date()).toISOString()))();
  const email = deps.email ?? new NoopEmailAdapter();
  try {
    const active = await deps.storage.findActiveDuplicate(input);
    if (active) {
      return {
        response: {
          ok: true,
          status: "already_exists",
          email_delivery: email.isEnabled() ? "skipped" : "disabled"
        },
        httpStatus: 200,
        analytics: {
          outcome: "already_exists",
          asset: input.asset,
          alert_scope: input.alert_scope
        }
      };
    }
    const unsubscribed = await deps.storage.findUnsubscribedDuplicate(input);
    let created;
    if (unsubscribed) {
      created = await deps.storage.reactivate(unsubscribed, input, {
        unsubscribe_token: createUnsubscribeToken(),
        now
      });
    } else {
      created = await deps.storage.create(input, {
        id: createId(),
        unsubscribe_token: createUnsubscribeToken(),
        now
      });
    }
    let delivery = email.isEnabled() ? "skipped" : "disabled";
    if (email.isEnabled()) {
      const origin = (deps.siteOrigin || "https://coinnavigator.net").replace(/\/$/, "");
      const status = await email.sendAlertConfirmation({
        to: created.email,
        asset: created.asset,
        alertScope: created.alert_scope,
        unsubscribeUrl: `${origin}/api/alerts/unsubscribe?token=${created.unsubscribe_token}`
      });
      delivery = status === "queued" ? "queued" : status === "disabled" ? "disabled" : "skipped";
    }
    return {
      response: {
        ok: true,
        status: "created",
        email_delivery: delivery
      },
      httpStatus: 201,
      analytics: {
        outcome: "created",
        asset: input.asset,
        alert_scope: input.alert_scope
      }
    };
  } catch (err) {
    if (err instanceof StorageConfigError) {
      return {
        response: {
          ok: false,
          error: {
            code: "MISSING_CONFIG",
            message: "Alert storage is temporarily unavailable."
          }
        },
        httpStatus: 503,
        analytics: {
          outcome: "failed",
          failure_category: "missing_config",
          asset: input.asset,
          alert_scope: input.alert_scope
        }
      };
    }
    if (err instanceof StorageFailureError) {
      return {
        response: {
          ok: false,
          error: {
            code: "SERVER_ERROR",
            message: "Unable to save your alert right now. Please try again later."
          }
        },
        httpStatus: 503,
        analytics: {
          outcome: "failed",
          failure_category: "storage_failure",
          asset: input.asset,
          alert_scope: input.alert_scope
        }
      };
    }
    return {
      response: {
        ok: false,
        error: {
          code: "SERVER_ERROR",
          message: "Unable to save your alert right now. Please try again later."
        }
      },
      httpStatus: 500,
      analytics: {
        outcome: "failed",
        failure_category: "server_error",
        asset: input.asset,
        alert_scope: input.alert_scope
      }
    };
  }
}

// src/alerts/supabase-storage.ts
function getConfig(env = process.env) {
  const url = (env.SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || "").trim().replace(/\/$/, "");
  const serviceRoleKey = (env.SUPABASE_SERVICE_ROLE_KEY || "").trim();
  if (!url || !serviceRoleKey) return null;
  return { url, serviceRoleKey };
}
function mapRow(row) {
  return {
    id: String(row.id),
    email: String(row.email),
    asset: row.asset,
    buy_exchange: row.buy_exchange ?? null,
    sell_exchange: row.sell_exchange ?? null,
    alert_scope: row.alert_scope,
    minimum_net_profit_pct: row.minimum_net_profit_pct === null || row.minimum_net_profit_pct === void 0 ? null : Number(row.minimum_net_profit_pct),
    minimum_net_profit_usd: row.minimum_net_profit_usd === null || row.minimum_net_profit_usd === void 0 ? null : Number(row.minimum_net_profit_usd),
    source_page: String(row.source_page ?? ""),
    source_context: String(row.source_context ?? ""),
    created_at: String(row.created_at),
    updated_at: String(row.updated_at),
    status: row.status,
    unsubscribe_token: String(row.unsubscribe_token),
    consent_version: String(row.consent_version ?? ""),
    user_agent_hash: row.user_agent_hash == null ? null : String(row.user_agent_hash),
    latest_matching_opportunity_at: row.latest_matching_opportunity_at == null ? null : String(row.latest_matching_opportunity_at)
  };
}
async function rest(cfg, path, init = {}) {
  const headers = {
    apikey: cfg.serviceRoleKey,
    Authorization: `Bearer ${cfg.serviceRoleKey}`,
    "Content-Type": "application/json"
  };
  if (init.prefer) headers.Prefer = init.prefer;
  const res = await fetch(`${cfg.url}/rest/v1/${path}`, {
    ...init,
    headers: { ...headers, ...init.headers }
  });
  const text = await res.text();
  let json = null;
  if (text) {
    try {
      json = JSON.parse(text);
    } catch {
      json = null;
    }
  }
  return { status: res.status, json, text };
}
var SupabaseAlertStorage = class _SupabaseAlertStorage {
  constructor(cfg) {
    this.cfg = cfg;
  }
  static fromEnv(env = process.env) {
    const cfg = getConfig(env);
    return cfg ? new _SupabaseAlertStorage(cfg) : null;
  }
  async findByStatus(input, statusFilter) {
    let query = `arbitrage_alerts?select=*&email=eq.${encodeURIComponent(input.email)}&asset=eq.${encodeURIComponent(input.asset)}&alert_scope=eq.${encodeURIComponent(input.alert_scope)}&status=${statusFilter}&limit=20`;
    if (input.alert_scope === "exact_pair") {
      query += `&buy_exchange=eq.${encodeURIComponent(String(input.buy_exchange))}&sell_exchange=eq.${encodeURIComponent(String(input.sell_exchange))}`;
    }
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByStatus failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async findActiveDuplicate(input) {
    return this.findByStatus(input, "in.(pending,active)");
  }
  async findUnsubscribedDuplicate(input) {
    return this.findByStatus(input, "eq.unsubscribed");
  }
  async findByUnsubscribeToken(token) {
    const query = `arbitrage_alerts?select=*&unsubscribe_token=eq.${encodeURIComponent(token)}&limit=1`;
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByToken failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async create(input, meta) {
    const payload = {
      id: meta.id,
      email: input.email,
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      created_at: meta.now,
      updated_at: meta.now,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      latest_matching_opportunity_at: null
    };
    const { status, json, text } = await rest(
      this.cfg,
      "arbitrage_alerts",
      {
        method: "POST",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`create failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async reactivate(existing, input, meta) {
    const payload = {
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      updated_at: meta.now
    };
    const { status, json, text } = await rest(
      this.cfg,
      `arbitrage_alerts?id=eq.${encodeURIComponent(existing.id)}`,
      {
        method: "PATCH",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`reactivate failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async markUnsubscribed(token, now) {
    const existing = await this.findByUnsubscribeToken(token);
    if (!existing) return "not_found";
    if (existing.status === "unsubscribed") return "already_unsubscribed";
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alerts?unsubscribe_token=eq.${encodeURIComponent(token)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ status: "unsubscribed", updated_at: now }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`unsubscribe failed (${status}): ${text.slice(0, 120)}`);
    }
    return "unsubscribed";
  }
};

// src/alerts/http.ts
var MAX_BODY_BYTES = 8 * 1024;
function header(req, name) {
  const raw = req.headers?.[name] ?? req.headers?.[name.toLowerCase()];
  if (Array.isArray(raw)) return raw[0] || "";
  return typeof raw === "string" ? raw : "";
}
function clientIp(req) {
  const fwd = header(req, "x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim().slice(0, 64);
  const real = header(req, "x-real-ip");
  if (real) return real.trim().slice(0, 64);
  return (req.socket?.remoteAddress || "unknown").slice(0, 64);
}
function readBody(req) {
  if (req.body == null) {
    return {
      ok: false,
      status: 400,
      response: {
        ok: false,
        error: { code: "VALIDATION_ERROR", message: "Please check the submitted details." }
      }
    };
  }
  if (typeof req.body === "string") {
    if (req.body.length > MAX_BODY_BYTES) {
      return {
        ok: false,
        status: 413,
        response: {
          ok: false,
          error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the submitted details." }
        }
      };
    }
    try {
      return { ok: true, value: JSON.parse(req.body) };
    } catch {
      return {
        ok: false,
        status: 400,
        response: {
          ok: false,
          error: { code: "VALIDATION_ERROR", message: "Please check the submitted details." }
        }
      };
    }
  }
  const encoded = JSON.stringify(req.body);
  if (encoded.length > MAX_BODY_BYTES) {
    return {
      ok: false,
      status: 413,
      response: {
        ok: false,
        error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the submitted details." }
      }
    };
  }
  return { ok: true, value: req.body };
}
function resolveStorage(env, injected) {
  if (injected) return injected;
  const supabase = SupabaseAlertStorage.fromEnv(env);
  if (supabase) return supabase;
  throw new StorageConfigError();
}
async function handleCreateAlertRequest(req, res, opts = {}) {
  res.setHeader("Cache-Control", "no-store");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  if (req.method === "OPTIONS") {
    res.setHeader("Allow", "POST, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "POST") {
    res.status(405).json({
      ok: false,
      error: { code: "METHOD_NOT_ALLOWED", message: "Please check the submitted details." }
    });
    return;
  }
  const contentType = header(req, "content-type").toLowerCase();
  if (!contentType.includes("application/json")) {
    res.status(415).json({
      ok: false,
      error: { code: "VALIDATION_ERROR", message: "Please check the submitted details." }
    });
    return;
  }
  const ip = clientIp(req);
  const rl = checkRateLimit(`alerts:create:${ip}`);
  if (!rl.allowed) {
    res.setHeader("Retry-After", String(rl.retryAfterSec));
    res.status(429).json({
      ok: false,
      error: {
        code: "RATE_LIMITED",
        message: "Too many requests. Please try again later."
      }
    });
    return;
  }
  const body = readBody(req);
  if (!body.ok) {
    res.status(body.status).json(body.response);
    return;
  }
  const env = opts.env ?? process.env;
  let storage;
  try {
    storage = resolveStorage(env, opts.storage);
  } catch {
    res.status(503).json({
      ok: false,
      error: {
        code: "MISSING_CONFIG",
        message: "Alert storage is temporarily unavailable."
      }
    });
    return;
  }
  const payload = body.value && typeof body.value === "object" ? {
    ...body.value,
    user_agent: header(req, "user-agent")
  } : body.value;
  const result = await createAlertSubscription(payload, {
    storage,
    email: getEmailAdapter(env),
    siteOrigin: env.ALERTS_SITE_ORIGIN || "https://coinnavigator.net"
  });
  res.status(result.httpStatus).json(result.response);
}

// src/alerts/vercel/create.ts
async function handler(req, res) {
  await handleCreateAlertRequest(req, res);
}
export {
  handler as default
};
