// Generated by tsup from src/alerts — do not edit by hand.


// src/alerts/email.ts
function parseResendId(json) {
  if (!json || typeof json !== "object") return null;
  const id = json.id;
  return typeof id === "string" && id.trim() ? id.trim().slice(0, 128) : null;
}
var ResendEmailAdapter = class _ResendEmailAdapter {
  constructor(apiKey, fromAddress) {
    this.apiKey = apiKey;
    this.fromAddress = fromAddress;
  }
  static fromEnv(env = process.env) {
    const apiKey = (env.RESEND_API_KEY || "").trim();
    if (!apiKey) return null;
    const fromAddress = (env.ALERTS_FROM_EMAIL || "CoinNavigator Alerts <alerts@coinnavigator.net>").trim();
    return new _ResendEmailAdapter(apiKey, fromAddress);
  }
  isEnabled() {
    return Boolean(this.apiKey);
  }
  async sendAlertConfirmation(payload) {
    if (!this.isEnabled()) return "disabled";
    try {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          from: this.fromAddress,
          to: [payload.to],
          subject: "CoinNavigator alert subscription confirmed",
          text: [
            `Your CoinNavigator opportunity alert for ${payload.asset} (${payload.alertScope}) is active.`,
            "",
            "Alerts are estimates, not financial advice. Market conditions may change before execution.",
            "",
            `Unsubscribe: ${payload.unsubscribeUrl}`
          ].join("\n")
        })
      });
      if (!res.ok) return "failed";
      return "queued";
    } catch {
      return "failed";
    }
  }
  async sendOpportunityEmail(payload) {
    if (!this.isEnabled()) {
      return {
        status: "disabled",
        provider: null,
        messageId: null,
        failureCategory: "missing_config"
      };
    }
    try {
      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${this.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          from: this.fromAddress,
          to: [payload.to],
          subject: payload.subject,
          text: payload.text,
          html: payload.html
        })
      });
      if (!res.ok) {
        return {
          status: "failed",
          provider: "resend",
          messageId: null,
          failureCategory: res.status >= 500 ? "provider_unavailable" : "provider_rejected"
        };
      }
      let json = null;
      try {
        json = await res.json();
      } catch {
        json = null;
      }
      return {
        status: "queued",
        provider: "resend",
        messageId: parseResendId(json),
        failureCategory: null
      };
    } catch {
      return {
        status: "failed",
        provider: "resend",
        messageId: null,
        failureCategory: "provider_unavailable"
      };
    }
  }
};
var NoopEmailAdapter = class {
  isEnabled() {
    return false;
  }
  async sendAlertConfirmation() {
    return "disabled";
  }
  async sendOpportunityEmail() {
    return {
      status: "disabled",
      provider: null,
      messageId: null,
      failureCategory: "missing_config"
    };
  }
};
function getEmailAdapter(env = process.env) {
  return ResendEmailAdapter.fromEnv(env) ?? new NoopEmailAdapter();
}

// src/alerts/tokens.ts
import { createHash, randomBytes } from "crypto";
function createId() {
  return randomBytes(16).toString("hex");
}

// src/net-profit/config.ts
var NET_PROFIT_THRESHOLDS = {
  marginalProfitUsd: 1,
  marginalProfitPct: 0.05,
  costDominanceRatio: 0.7
};
var EXCHANGE_FEE_ESTIMATES = {
  Binance: {
    id: "Binance",
    displayName: "Binance",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.binance.com/en/fee/schedule",
    sourceNote: "Default spot VIP0 schedule (estimate). BNB discounts not applied.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Binance"
  },
  MEXC: {
    id: "MEXC",
    displayName: "MEXC",
    estimatedSpotMakerFeePct: 0,
    estimatedSpotTakerFeePct: 0.05,
    sourceUrl: "https://www.mexc.com/fee",
    sourceNote: "Default spot schedule (estimate). Maker often 0%; taker ~0.05%.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "MEXC"
  },
  Bybit: {
    id: "Bybit",
    displayName: "Bybit",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.bybit.com/en/help-center/article/Trading-Fee-Structure",
    sourceNote: "Default spot VIP0 schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Bybit"
  },
  OKX: {
    id: "OKX",
    displayName: "OKX",
    estimatedSpotMakerFeePct: 0.08,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.okx.com/fees",
    sourceNote: "Default spot VIP0 schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "OKX"
  },
  KuCoin: {
    id: "KuCoin",
    displayName: "KuCoin",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.kucoin.com/rate",
    sourceNote: "Default spot schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "KuCoin"
  },
  Gate: {
    id: "Gate",
    displayName: "Gate.io",
    estimatedSpotMakerFeePct: 0.2,
    estimatedSpotTakerFeePct: 0.2,
    sourceUrl: "https://www.gate.io/fee",
    sourceNote: "Default spot schedule (estimate). Higher than peers on many pairs.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Gate"
  }
};
var SUPPORTED_EXCHANGES = Object.freeze(
  Object.keys(EXCHANGE_FEE_ESTIMATES)
);
function getExchangeFeeEstimate(exchange) {
  if (Object.prototype.hasOwnProperty.call(EXCHANGE_FEE_ESTIMATES, exchange)) {
    return EXCHANGE_FEE_ESTIMATES[exchange];
  }
  return void 0;
}
function getEstimatedTakerFeePct(exchange) {
  const row = getExchangeFeeEstimate(exchange);
  return row ? row.estimatedSpotTakerFeePct : null;
}

// src/net-profit/validate.ts
import Decimal from "decimal.js";
Decimal.set({
  precision: 28,
  rounding: Decimal.ROUND_HALF_UP
});
function d(value) {
  return new Decimal(value);
}
function toNumber(value) {
  return value.toNumber();
}
function isFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value);
}
function validateNetProfitInput(input) {
  const issues = [];
  function requireFinite(field, value) {
    if (!isFiniteNumber(value)) {
      issues.push({ field, message: `${field} must be a finite number` });
    }
  }
  function requirePositive(field, value) {
    if (!(value > 0)) {
      issues.push({ field, message: `${field} must be greater than zero` });
    }
  }
  function requireNonNegative(field, value) {
    if (value < 0) {
      issues.push({ field, message: `${field} must be >= 0` });
    }
  }
  requireFinite("investmentUsd", input.investmentUsd);
  requireFinite("buyPrice", input.buyPrice);
  requireFinite("sellPrice", input.sellPrice);
  requireFinite("buyTradingFeePct", input.buyTradingFeePct);
  requireFinite("sellTradingFeePct", input.sellTradingFeePct);
  requireFinite("withdrawalFeeAsset", input.withdrawalFeeAsset);
  requireFinite("buySlippagePct", input.buySlippagePct);
  requireFinite("sellSlippagePct", input.sellSlippagePct);
  if (issues.length > 0) return issues;
  requirePositive("investmentUsd", input.investmentUsd);
  requirePositive("buyPrice", input.buyPrice);
  requirePositive("sellPrice", input.sellPrice);
  requireNonNegative("buyTradingFeePct", input.buyTradingFeePct);
  requireNonNegative("sellTradingFeePct", input.sellTradingFeePct);
  requireNonNegative("withdrawalFeeAsset", input.withdrawalFeeAsset);
  requireNonNegative("buySlippagePct", input.buySlippagePct);
  requireNonNegative("sellSlippagePct", input.sellSlippagePct);
  if (typeof input.assetSymbol !== "string" || input.assetSymbol.trim() === "") {
    issues.push({ field: "assetSymbol", message: "assetSymbol is required" });
  }
  if (typeof input.buyExchange !== "string" || input.buyExchange.trim() === "") {
    issues.push({ field: "buyExchange", message: "buyExchange is required" });
  }
  if (typeof input.sellExchange !== "string" || input.sellExchange.trim() === "") {
    issues.push({ field: "sellExchange", message: "sellExchange is required" });
  }
  if (input.networkFeeAsset !== void 0) {
    if (!isFiniteNumber(input.networkFeeAsset)) {
      issues.push({ field: "networkFeeAsset", message: "networkFeeAsset must be a finite number" });
    } else if (input.networkFeeAsset < 0) {
      issues.push({ field: "networkFeeAsset", message: "networkFeeAsset must be >= 0" });
    }
  }
  if (input.additionalCostUsd !== void 0) {
    if (!isFiniteNumber(input.additionalCostUsd)) {
      issues.push({ field: "additionalCostUsd", message: "additionalCostUsd must be a finite number" });
    } else if (input.additionalCostUsd < 0) {
      issues.push({ field: "additionalCostUsd", message: "additionalCostUsd must be >= 0" });
    }
  }
  return issues;
}

// src/net-profit/calculate.ts
function invalidResult(warnings) {
  return {
    purchasedQty: 0,
    sellableQty: 0,
    grossSpreadPct: 0,
    grossProfitUsd: 0,
    buyTradingFeeUsd: 0,
    sellTradingFeeUsd: 0,
    withdrawalCostAsset: 0,
    withdrawalCostUsd: 0,
    networkCostUsd: 0,
    estimatedSlippageCostUsd: 0,
    additionalCostUsd: 0,
    totalEstimatedCostsUsd: 0,
    netProceedsUsd: 0,
    estimatedNetProfitUsd: 0,
    netProfitPct: 0,
    breakEvenSpreadPct: 0,
    verdict: "invalid",
    warnings
  };
}
function roundMoney(value) {
  return toNumber(value.toDecimalPlaces(8, Decimal.ROUND_HALF_UP));
}
function roundPct(value) {
  return toNumber(value.toDecimalPlaces(8, Decimal.ROUND_HALF_UP));
}
function calculateNetProfit(input) {
  const issues = validateNetProfitInput(input);
  if (issues.length > 0) {
    return invalidResult(issues.map((i) => i.message));
  }
  const warnings = [];
  const investment = d(input.investmentUsd);
  const buyPrice = d(input.buyPrice);
  const sellPrice = d(input.sellPrice);
  const buyFeePct = d(input.buyTradingFeePct).div(100);
  const sellFeePct = d(input.sellTradingFeePct).div(100);
  const buySlipPct = d(input.buySlippagePct).div(100);
  const sellSlipPct = d(input.sellSlippagePct).div(100);
  const withdrawalAsset = d(input.withdrawalFeeAsset);
  const networkAsset = d(input.networkFeeAsset ?? 0);
  const additionalUsd = d(input.additionalCostUsd ?? 0);
  if (buyPrice.eq(sellPrice)) {
    warnings.push("Buy and sell prices are identical \u2014 gross spread is zero.");
  }
  const grossSpreadPct = sellPrice.minus(buyPrice).div(buyPrice).mul(100);
  const grossProfitUsd = investment.mul(sellPrice.minus(buyPrice)).div(buyPrice);
  const effectiveBuyPrice = buyPrice.mul(d(1).plus(buySlipPct));
  const effectiveSellPrice = sellPrice.mul(d(1).minus(sellSlipPct));
  if (effectiveSellPrice.lte(0)) {
    return invalidResult(["Sell slippage reduces effective sell price to zero or below."]);
  }
  const purchasedQty = investment.div(effectiveBuyPrice);
  const sellableQty = purchasedQty.minus(withdrawalAsset).minus(networkAsset);
  if (sellableQty.lte(0)) {
    warnings.push(
      "Withdrawal + network fees in asset units meet or exceed the purchased quantity."
    );
    return {
      ...invalidResult(warnings),
      purchasedQty: roundMoney(purchasedQty),
      sellableQty: 0,
      additionalCostUsd: roundMoney(additionalUsd),
      grossSpreadPct: roundPct(grossSpreadPct),
      grossProfitUsd: roundMoney(grossProfitUsd),
      withdrawalCostAsset: roundMoney(withdrawalAsset),
      withdrawalCostUsd: roundMoney(withdrawalAsset.mul(effectiveSellPrice)),
      networkCostUsd: roundMoney(networkAsset.mul(effectiveSellPrice)),
      verdict: "invalid"
    };
  }
  const buyTradingFeeUsd = investment.mul(buyFeePct);
  const sellNotionalUsd = sellableQty.mul(effectiveSellPrice);
  const sellTradingFeeUsd = sellNotionalUsd.mul(sellFeePct);
  const withdrawalCostUsd = withdrawalAsset.mul(effectiveSellPrice);
  const networkCostUsd = networkAsset.mul(effectiveSellPrice);
  const idealQty = investment.div(buyPrice);
  const idealSellable = Decimal.max(idealQty.minus(withdrawalAsset).minus(networkAsset), 0);
  const idealProceeds = idealSellable.mul(sellPrice);
  const slippedProceeds = sellableQty.mul(effectiveSellPrice);
  const estimatedSlippageCostUsd = Decimal.max(idealProceeds.minus(slippedProceeds), 0);
  const totalEstimatedCostsUsd = buyTradingFeeUsd.plus(sellTradingFeeUsd).plus(withdrawalCostUsd).plus(networkCostUsd).plus(estimatedSlippageCostUsd).plus(additionalUsd);
  const netProceedsUsd = sellNotionalUsd.minus(sellTradingFeeUsd);
  const estimatedNetProfitUsd = netProceedsUsd.minus(investment).minus(buyTradingFeeUsd).minus(additionalUsd);
  const netProfitPct = estimatedNetProfitUsd.div(investment).mul(100);
  const breakEvenSpreadPct = totalEstimatedCostsUsd.div(investment).mul(100);
  if (grossProfitUsd.gt(0) && totalEstimatedCostsUsd.div(grossProfitUsd).gte(NET_PROFIT_THRESHOLDS.costDominanceRatio)) {
    warnings.push(
      `Estimated costs consume \u2265 ${NET_PROFIT_THRESHOLDS.costDominanceRatio * 100}% of gross spread profit.`
    );
  }
  if (estimatedSlippageCostUsd.gte(grossProfitUsd) && grossProfitUsd.gt(0)) {
    warnings.push("Estimated slippage alone consumes the full gross spread profit.");
  }
  if (input.buyExchange === input.sellExchange) {
    warnings.push("Buy and sell exchanges are the same \u2014 this is not a cross-exchange arb.");
  }
  let verdict;
  if (estimatedNetProfitUsd.lte(0)) {
    verdict = "not_profitable";
  } else if (estimatedNetProfitUsd.lt(NET_PROFIT_THRESHOLDS.marginalProfitUsd) || netProfitPct.lt(NET_PROFIT_THRESHOLDS.marginalProfitPct)) {
    verdict = "marginal";
    warnings.push(
      `Net profit is below the safety threshold ($${NET_PROFIT_THRESHOLDS.marginalProfitUsd} or ${NET_PROFIT_THRESHOLDS.marginalProfitPct}%).`
    );
  } else {
    verdict = "profitable";
  }
  return {
    purchasedQty: roundMoney(purchasedQty),
    sellableQty: roundMoney(sellableQty),
    grossSpreadPct: roundPct(grossSpreadPct),
    grossProfitUsd: roundMoney(grossProfitUsd),
    buyTradingFeeUsd: roundMoney(buyTradingFeeUsd),
    sellTradingFeeUsd: roundMoney(sellTradingFeeUsd),
    withdrawalCostAsset: roundMoney(withdrawalAsset),
    withdrawalCostUsd: roundMoney(withdrawalCostUsd),
    networkCostUsd: roundMoney(networkCostUsd),
    estimatedSlippageCostUsd: roundMoney(estimatedSlippageCostUsd),
    additionalCostUsd: roundMoney(additionalUsd),
    totalEstimatedCostsUsd: roundMoney(totalEstimatedCostsUsd),
    netProceedsUsd: roundMoney(netProceedsUsd),
    estimatedNetProfitUsd: roundMoney(estimatedNetProfitUsd),
    netProfitPct: roundPct(netProfitPct),
    breakEvenSpreadPct: roundPct(breakEvenSpreadPct),
    verdict,
    warnings
  };
}

// src/alerts/match/policies.ts
var MATCHER_STALE_MS = 20 * 60 * 1e3;
var DEFAULT_MIN_NET_PROFIT_PCT = 0.25;
var ROUTE_COOLDOWN_MS = 6 * 60 * 60 * 1e3;
var MATERIAL_IMPROVEMENT_PCT_POINTS = 0.5;
var ALERT_BATCH_SIZE = 50;
var EMAIL_CONCURRENCY = 2;

// src/alerts/match/evaluate.ts
function thresholdsPass(alert, netPct, netUsd) {
  const hasPct = alert.minimum_net_profit_pct != null && Number.isFinite(alert.minimum_net_profit_pct);
  const hasUsd = alert.minimum_net_profit_usd != null && Number.isFinite(alert.minimum_net_profit_usd);
  if (!hasPct && !hasUsd) {
    return netPct >= DEFAULT_MIN_NET_PROFIT_PCT;
  }
  if (hasPct && netPct < Number(alert.minimum_net_profit_pct)) return false;
  if (hasUsd && netUsd < Number(alert.minimum_net_profit_usd)) return false;
  return true;
}
function evaluateOpportunity(alert, opp, opts = {}) {
  if (alert.status === "unsubscribed") return { ok: false, reason: "unsubscribed" };
  if (alert.status !== "active") return { ok: false, reason: "not_active" };
  const amount = alert.trade_amount_usd;
  if (amount == null || !Number.isFinite(amount) || amount <= 0) {
    return { ok: false, reason: "missing_trade_amount" };
  }
  if (alert.alert_scope === "exact_pair") {
    if (!alert.buy_exchange || !alert.sell_exchange) {
      return { ok: false, reason: "unsupported_route" };
    }
    if (opp.buyExchange !== alert.buy_exchange || opp.sellExchange !== alert.sell_exchange) {
      return { ok: false, reason: "no_matching_opportunity" };
    }
  } else if (alert.asset !== opp.asset) {
    return { ok: false, reason: "no_matching_opportunity" };
  }
  if (alert.asset !== opp.asset) return { ok: false, reason: "no_matching_opportunity" };
  const buyFee = getEstimatedTakerFeePct(opp.buyExchange);
  const sellFee = getEstimatedTakerFeePct(opp.sellExchange);
  if (buyFee == null || sellFee == null) {
    return { ok: false, reason: "unknown_trading_fee" };
  }
  const result = calculateNetProfit({
    investmentUsd: amount,
    buyExchange: opp.buyExchange,
    sellExchange: opp.sellExchange,
    assetSymbol: opp.asset,
    buyPrice: opp.buyPrice,
    sellPrice: opp.sellPrice,
    buyTradingFeePct: buyFee,
    sellTradingFeePct: sellFee,
    // Unknown transfer costs are NOT treated as verified zero in product copy.
    // Engine requires a number; 0 is math-only and is labeled unavailable below.
    withdrawalFeeAsset: 0,
    networkFeeAsset: 0,
    buySlippagePct: 0,
    sellSlippagePct: 0,
    additionalCostUsd: 0
  });
  if (result.verdict === "invalid") {
    return { ok: false, reason: "invalid_financials" };
  }
  if (!thresholdsPass(alert, result.netProfitPct, result.estimatedNetProfitUsd)) {
    return { ok: false, reason: "below_threshold" };
  }
  const now = (opts.now ?? (() => /* @__PURE__ */ new Date()))();
  const warnings = [
    ...result.warnings ?? [],
    "Trading fees are VIP0-style estimates, not live account rates.",
    "Withdrawal and network fees are unavailable and were not treated as verified zero. Estimated net excludes unknown transfer costs.",
    "Slippage is not modeled from a live order book. Run Validate Live Route before trading.",
    "Prices can change before you finish transferring and trading."
  ];
  return {
    ok: true,
    match: {
      matched: true,
      asset: alert.asset,
      buyExchange: opp.buyExchange,
      sellExchange: opp.sellExchange,
      tradeAmountUsd: amount,
      buyPrice: opp.buyPrice,
      sellPrice: opp.sellPrice,
      grossSpreadPct: result.grossSpreadPct,
      estimatedNetProfitUsd: result.estimatedNetProfitUsd,
      estimatedNetProfitPct: result.netProfitPct,
      dataTimestamp: opp.dataTimestamp,
      matchedAt: now.toISOString(),
      assumptions: {
        buyFeePct: buyFee,
        sellFeePct: sellFee,
        buyFeeKind: "estimated",
        sellFeeKind: "estimated",
        withdrawalFeeKind: "unavailable",
        networkFeeKind: "unavailable",
        slippageKind: "unavailable"
      },
      warnings
    }
  };
}
function pickBestCandidate(alert, candidates, opts = {}) {
  let best = null;
  let lastFail = "no_matching_opportunity";
  for (const opp of candidates) {
    const evaluated = evaluateOpportunity(alert, opp, opts);
    if (!evaluated.ok) {
      lastFail = evaluated.reason;
      continue;
    }
    if (!best || evaluated.match.estimatedNetProfitPct > best.estimatedNetProfitPct) {
      best = evaluated.match;
    }
  }
  if (!best) return { ok: false, reason: lastFail };
  return { ok: true, match: best };
}

// src/alerts/match/fingerprint.ts
import { createHash as createHash2 } from "crypto";
function opportunityEventFingerprint(input) {
  const raw = [
    "event",
    input.asset,
    input.buyExchange,
    input.sellExchange,
    input.dataTimestamp
  ].join("|");
  return createHash2("sha256").update(raw).digest("hex").slice(0, 40);
}
function opportunityImprovementFingerprint(input) {
  const raw = [
    "improve",
    input.asset,
    input.buyExchange,
    input.sellExchange,
    input.netPctRounded
  ].join("|");
  return createHash2("sha256").update(raw).digest("hex").slice(0, 40);
}

// src/alerts/allowlist.ts
var SUPPORTED_EXCHANGES2 = [
  "Binance",
  "MEXC",
  "Bybit",
  "OKX",
  "KuCoin",
  "Gate"
];
var SUPPORTED_ASSETS = [
  "BTC",
  "ETH",
  "SOL",
  "XRP",
  "TON",
  "DOGE",
  "ADA",
  "BNB",
  "TRX",
  "DOT",
  "LINK",
  "LTC",
  "AVAX",
  "MATIC",
  "SHIB",
  "UNI",
  "XLM",
  "NEAR",
  "ATOM",
  "APT"
];
var EXCHANGE_SET = new Set(SUPPORTED_EXCHANGES2);
var ASSET_SET = new Set(SUPPORTED_ASSETS);
var EXCHANGE_ALIASES = {
  gate: "Gate",
  "gate.io": "Gate",
  gateio: "Gate",
  binance: "Binance",
  mexc: "MEXC",
  bybit: "Bybit",
  okx: "OKX",
  kucoin: "KuCoin"
};
function normalizeExchange(raw) {
  if (typeof raw !== "string") return null;
  const trimmed = raw.trim();
  if (!trimmed) return null;
  if (EXCHANGE_SET.has(trimmed)) return trimmed;
  const alias = EXCHANGE_ALIASES[trimmed.toLowerCase()];
  return alias ?? null;
}

// src/alerts/match/opportunities.ts
function parseSpreadSnapshot(raw) {
  if (!raw || typeof raw !== "object") return null;
  const body = raw;
  if (typeof body.timestamp !== "string" || !body.timestamp.trim()) return null;
  if (!body.symbols || typeof body.symbols !== "object") return null;
  const ts = Date.parse(body.timestamp);
  if (!Number.isFinite(ts)) return null;
  return {
    timestamp: body.timestamp,
    symbols: body.symbols
  };
}
function snapshotAgeMs(snapshot, now = Date.now()) {
  const ts = Date.parse(snapshot.timestamp);
  if (!Number.isFinite(ts)) return Number.POSITIVE_INFINITY;
  return Math.max(0, now - ts);
}
function validPrice(n) {
  return typeof n === "number" && Number.isFinite(n) && n > 0;
}
function extractOpportunitiesForAsset(snapshot, asset) {
  const symbol = `${asset}USDT`;
  const row = snapshot.symbols[symbol];
  if (!row || typeof row !== "object") return [];
  const prices = row.prices || {};
  const exchanges = [];
  const priceMap = /* @__PURE__ */ new Map();
  for (const [name, price] of Object.entries(prices)) {
    const ex = normalizeExchange(name);
    if (!ex || !validPrice(price)) continue;
    priceMap.set(ex, price);
    exchanges.push(ex);
  }
  const out = [];
  for (const buy of exchanges) {
    for (const sell of exchanges) {
      if (buy === sell) continue;
      const buyPrice = priceMap.get(buy);
      const sellPrice = priceMap.get(sell);
      if (!validPrice(buyPrice) || !validPrice(sellPrice)) continue;
      if (sellPrice <= buyPrice) continue;
      out.push({
        asset,
        symbol,
        buyExchange: buy,
        sellExchange: sell,
        buyPrice,
        sellPrice,
        dataTimestamp: snapshot.timestamp
      });
    }
  }
  return out;
}

// src/alerts/match/opportunity-email.ts
function escapeHtml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function fmtUsd(n) {
  const sign = n < 0 ? "-" : "";
  return `${sign}$${Math.abs(n).toFixed(2)}`;
}
function fmtPct(n) {
  const sign = n > 0 ? "+" : "";
  return `${sign}${n.toFixed(4)}%`;
}
function buildReturnUrl(siteOrigin, match) {
  const origin = siteOrigin.replace(/\/$/, "");
  const q = new URLSearchParams({
    asset: match.asset,
    buy: match.buyExchange,
    sell: match.sellExchange,
    utm_source: "alert_email",
    utm_medium: "email",
    utm_campaign: "arbitrage_alert"
  });
  return `${origin}/?${q.toString()}`;
}
function opportunityEmailSubject(match) {
  return `${match.asset} arbitrage opportunity detected`;
}
function opportunityEmailText(payload) {
  const m = payload.match;
  return [
    `${m.asset} arbitrage candidate detected by CoinNavigator.`,
    "",
    `Buy: ${m.buyExchange} @ ${m.buyPrice}`,
    `Sell: ${m.sellExchange} @ ${m.sellPrice}`,
    `Gross spread: ${fmtPct(m.grossSpreadPct)}`,
    `Estimated net profit: ${fmtPct(m.estimatedNetProfitPct)} (${fmtUsd(m.estimatedNetProfitUsd)})`,
    `Trade amount used for this estimate: ${fmtUsd(m.tradeAmountUsd)}`,
    `Market data timestamp: ${m.dataTimestamp}`,
    "",
    "This is an estimate based on a CoinNavigator snapshot, estimated trading fees, and incomplete transfer-cost data.",
    "Withdrawal/network fees were unavailable and were not treated as zero.",
    "Prices, liquidity, fees and transfer availability can change before execution.",
    "This is not financial advice. CoinNavigator does not execute trades.",
    "",
    `Open CoinNavigator and run Validate Live Route: ${payload.ctaUrl}`,
    "",
    `Unsubscribe: ${payload.unsubscribeUrl}`
  ].join("\n");
}
function opportunityEmailHtml(payload) {
  const m = payload.match;
  const rows = [
    ["Asset", m.asset],
    ["Buy exchange", m.buyExchange],
    ["Observed buy price", String(m.buyPrice)],
    ["Sell exchange", m.sellExchange],
    ["Observed sell price", String(m.sellPrice)],
    ["Gross spread", fmtPct(m.grossSpreadPct)],
    ["Estimated net profit %", fmtPct(m.estimatedNetProfitPct)],
    ["Estimated net profit (USD)", fmtUsd(m.estimatedNetProfitUsd)],
    ["Trade amount used", fmtUsd(m.tradeAmountUsd)],
    ["Market data timestamp", m.dataTimestamp]
  ];
  const table = rows.map(
    ([k, v]) => `<tr><td style="padding:6px 8px;color:#64748b;">${escapeHtml(String(k))}</td><td style="padding:6px 8px;font-weight:700;">${escapeHtml(String(v))}</td></tr>`
  ).join("");
  return `<!DOCTYPE html>
<html><body style="font-family:system-ui,sans-serif;line-height:1.45;color:#0f172a;">
  <h1 style="font-size:18px;">${escapeHtml(m.asset)} arbitrage opportunity detected</h1>
  <p>CoinNavigator found a candidate route that meets your alert thresholds. This is an <strong>estimated</strong> net result, not a promise of profit.</p>
  <table style="border-collapse:collapse;">${table}</table>
  <p style="font-size:13px;color:#475569;">Trading fees are estimates. Withdrawal and network fees were unavailable and were <strong>not</strong> treated as verified zero. Markets can move before you finish transferring and trading. CoinNavigator does not execute trades and this is not financial advice.</p>
  <p><a href="${escapeHtml(payload.ctaUrl)}" style="display:inline-block;background:#4f46e5;color:#fff;padding:10px 14px;border-radius:8px;text-decoration:none;font-weight:700;">Open CoinNavigator \u2014 Validate Live Route</a></p>
  <p style="font-size:12px;color:#64748b;"><a href="${escapeHtml(payload.unsubscribeUrl)}">Unsubscribe from this alert</a></p>
</body></html>`;
}

// src/alerts/match/cooldown.ts
function netPctRounded(n) {
  return n.toFixed(2);
}
function decideCooldown(lastSent, match, nowMs) {
  if (!lastSent || !lastSent.sent_at) {
    return { action: "send", reason: "no_prior" };
  }
  const sentMs = Date.parse(lastSent.sent_at);
  if (!Number.isFinite(sentMs)) {
    return { action: "send", reason: "no_prior" };
  }
  if (nowMs - sentMs >= ROUTE_COOLDOWN_MS) {
    return { action: "send", reason: "cooldown_expired" };
  }
  const prevPct = lastSent.estimated_net_profit_pct == null ? null : Number(lastSent.estimated_net_profit_pct);
  if (prevPct != null && Number.isFinite(prevPct) && match.estimatedNetProfitPct >= prevPct + MATERIAL_IMPROVEMENT_PCT_POINTS) {
    return { action: "send", reason: "material_improvement" };
  }
  return { action: "skip", reason: "cooldown" };
}
var STALE_PENDING_RETRY_MS = 10 * 60 * 1e3;
function shouldRetryExisting(existing, nowMs) {
  if (existing.email_status === "failed") return true;
  if (existing.email_status === "pending") {
    const created = Date.parse(existing.created_at || existing.matched_at);
    if (!Number.isFinite(created)) return true;
    return nowMs - created >= STALE_PENDING_RETRY_MS;
  }
  return false;
}

// src/alerts/match/runner.ts
function emptySummary(dryRun, skip, durationMs) {
  return {
    ok: true,
    dry_run: dryRun,
    skip_reason: skip,
    alerts_checked: 0,
    opportunities_checked: 0,
    matches: 0,
    emails_sent: 0,
    emails_failed: 0,
    duplicates_skipped: 0,
    cooldown_skipped: 0,
    stale_data_skips: 0,
    missing_trade_amount: 0,
    duration_ms: durationMs
  };
}
async function listAllActive(storage) {
  const out = [];
  let afterId;
  for (; ; ) {
    const opts = afterId ? { afterId, limit: ALERT_BATCH_SIZE } : { limit: ALERT_BATCH_SIZE };
    const batch = await storage.listActiveAlerts(opts);
    if (!batch.length) break;
    out.push(...batch);
    afterId = batch[batch.length - 1].id;
    if (batch.length < ALERT_BATCH_SIZE) break;
  }
  return out;
}
async function mapPool(items, concurrency, fn) {
  if (!items.length) return;
  let i = 0;
  const workers = Array.from({ length: Math.min(concurrency, items.length) }, async () => {
    while (i < items.length) {
      const idx = i;
      i += 1;
      await fn(items[idx]);
    }
  });
  await Promise.all(workers);
}
function unsubscribeUrl(origin, token) {
  return `${origin.replace(/\/$/, "")}/api/alerts/unsubscribe?token=${token}`;
}
async function runAlertMatcher(deps) {
  const started = Date.now();
  const dryRun = Boolean(deps.dryRun);
  const nowFn = deps.now ?? (() => /* @__PURE__ */ new Date());
  const log = deps.log ?? ((entry) => console.log(JSON.stringify(entry)));
  const runId = createId();
  const age = snapshotAgeMs(deps.snapshot, nowFn().getTime());
  if (age > MATCHER_STALE_MS) {
    const summary2 = emptySummary(dryRun, "stale_data", Date.now() - started);
    summary2.stale_data_skips = 1;
    log({
      event: "alert_matcher_run",
      run_id: runId,
      dry_run: dryRun,
      skip_reason: "stale_data",
      snapshot_age_ms: age,
      duration_ms: summary2.duration_ms
    });
    return summary2;
  }
  const alerts = await listAllActive(deps.storage);
  const summary = {
    ok: true,
    dry_run: dryRun,
    skip_reason: !dryRun && !deps.email.isEnabled() ? "missing_config" : null,
    alerts_checked: alerts.length,
    opportunities_checked: 0,
    matches: 0,
    emails_sent: 0,
    emails_failed: 0,
    duplicates_skipped: 0,
    cooldown_skipped: 0,
    stale_data_skips: 0,
    missing_trade_amount: 0,
    duration_ms: 0
  };
  const work = [];
  const oppCache = /* @__PURE__ */ new Map();
  for (const alert of alerts) {
    if (alert.trade_amount_usd == null) {
      summary.missing_trade_amount += 1;
      continue;
    }
    let candidates = oppCache.get(alert.asset);
    if (!candidates) {
      candidates = extractOpportunitiesForAsset(deps.snapshot, alert.asset);
      oppCache.set(alert.asset, candidates);
      summary.opportunities_checked += candidates.length;
    }
    const evaluated = pickBestCandidate(alert, candidates, { now: nowFn });
    if (!evaluated.ok) continue;
    summary.matches += 1;
    work.push({ alert, match: evaluated.match });
  }
  await mapPool(work, EMAIL_CONCURRENCY, async ({ alert, match }) => {
    const now = nowFn();
    const nowMs = now.getTime();
    const eventFp = opportunityEventFingerprint({
      asset: match.asset,
      buyExchange: match.buyExchange,
      sellExchange: match.sellExchange,
      dataTimestamp: match.dataTimestamp
    });
    const existingEvent = await deps.storage.getDelivery(alert.id, eventFp);
    if (existingEvent && !shouldRetryExisting(existingEvent, nowMs)) {
      summary.duplicates_skipped += 1;
      return;
    }
    const lastSent = await deps.storage.getLastSentForRoute(
      alert.id,
      match.asset,
      match.buyExchange,
      match.sellExchange
    );
    const cooldown = decideCooldown(lastSent, match, nowMs);
    if (!existingEvent && cooldown.action === "skip") {
      summary.cooldown_skipped += 1;
      return;
    }
    const fingerprint = !existingEvent && cooldown.reason === "material_improvement" ? opportunityImprovementFingerprint({
      asset: match.asset,
      buyExchange: match.buyExchange,
      sellExchange: match.sellExchange,
      netPctRounded: netPctRounded(match.estimatedNetProfitPct)
    }) : eventFp;
    if (dryRun || !deps.email.isEnabled()) return;
    const existing = existingEvent ?? await deps.storage.getDelivery(alert.id, fingerprint);
    let deliveryId;
    if (existing) {
      if (!shouldRetryExisting(existing, nowMs)) {
        summary.duplicates_skipped += 1;
        return;
      }
      deliveryId = existing.id;
    } else {
      deliveryId = createId();
      const reserved = await deps.storage.insertDeliveryPending({
        id: deliveryId,
        alert_id: alert.id,
        opportunity_fingerprint: fingerprint,
        asset: match.asset,
        buy_exchange: match.buyExchange,
        sell_exchange: match.sellExchange,
        estimated_net_profit_pct: match.estimatedNetProfitPct,
        estimated_net_profit_usd: match.estimatedNetProfitUsd,
        opportunity_data_timestamp: match.dataTimestamp,
        matched_at: match.matchedAt,
        created_at: now.toISOString()
      });
      if (reserved === "duplicate") {
        summary.duplicates_skipped += 1;
        return;
      }
    }
    const origin = deps.siteOrigin.replace(/\/$/, "");
    const emailPayload = {
      to: alert.email,
      unsubscribeUrl: unsubscribeUrl(origin, alert.unsubscribe_token),
      ctaUrl: buildReturnUrl(origin, match),
      match
    };
    const sent = await deps.email.sendOpportunityEmail({
      to: alert.email,
      subject: opportunityEmailSubject(match),
      text: opportunityEmailText(emailPayload),
      html: opportunityEmailHtml(emailPayload)
    });
    if (sent.status === "queued") {
      await deps.storage.markDeliverySent(deliveryId, {
        sentAt: now.toISOString(),
        provider: sent.provider || "resend",
        providerMessageId: sent.messageId
      });
      await deps.storage.updateLatestMatchingOpportunity(alert.id, match.matchedAt);
      summary.emails_sent += 1;
      return;
    }
    await deps.storage.markDeliveryFailed(
      deliveryId,
      sent.failureCategory || "provider_unavailable"
    );
    summary.emails_failed += 1;
  });
  summary.duration_ms = Date.now() - started;
  log({
    event: "alert_matcher_run",
    run_id: runId,
    dry_run: dryRun,
    alerts_checked: summary.alerts_checked,
    opportunities_checked: summary.opportunities_checked,
    matches: summary.matches,
    emails_sent: summary.emails_sent,
    emails_failed: summary.emails_failed,
    duplicates_skipped: summary.duplicates_skipped,
    cooldown_skipped: summary.cooldown_skipped,
    stale_data_skips: summary.stale_data_skips,
    missing_trade_amount: summary.missing_trade_amount,
    skip_reason: summary.skip_reason,
    duration_ms: summary.duration_ms
  });
  return summary;
}

// src/alerts/match/snapshot.ts
import { readFile } from "fs/promises";
import { resolve } from "path";
async function readLocalJson(rel) {
  try {
    const text = await readFile(resolve(process.cwd(), rel), "utf8");
    return JSON.parse(text);
  } catch {
    return null;
  }
}
async function fetchJson(url, fetchImpl) {
  try {
    const res = await fetchImpl(url, {
      method: "GET",
      headers: { Accept: "application/json" }
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}
async function loadSpreadSnapshot(opts) {
  if (opts.injected !== void 0) {
    const parsed = parseSpreadSnapshot(opts.injected);
    return parsed ? { ok: true, snapshot: parsed, source: "injected" } : { ok: false, reason: "malformed" };
  }
  const env = opts.env ?? process.env;
  const localCandidates = ["data/spread_data.json", "spread_data.json"];
  for (const rel of localCandidates) {
    const raw = await readLocalJson(rel);
    if (raw == null) continue;
    const parsed = parseSpreadSnapshot(raw);
    if (parsed) return { ok: true, snapshot: parsed, source: rel };
    return { ok: false, reason: "malformed" };
  }
  const origin = (env.ALERTS_SITE_ORIGIN || "https://coinnavigator.net").replace(/\/$/, "");
  const fetchImpl = opts.fetchImpl ?? fetch;
  for (const path of ["/data/spread_data.json", "/spread_data.json"]) {
    const raw = await fetchJson(`${origin}${path}`, fetchImpl);
    if (raw == null) continue;
    const parsed = parseSpreadSnapshot(raw);
    if (parsed) return { ok: true, snapshot: parsed, source: `http:${path}` };
    return { ok: false, reason: "malformed" };
  }
  return { ok: false, reason: "unavailable" };
}

// src/alerts/storage.ts
var StorageConfigError = class extends Error {
  constructor(message = "Alert storage is not configured") {
    super(message);
    this.name = "StorageConfigError";
  }
};
var StorageFailureError = class extends Error {
  constructor(message = "Alert storage failed") {
    super(message);
    this.name = "StorageFailureError";
  }
};

// src/alerts/supabase-storage.ts
function getConfig(env = process.env) {
  const url = (env.SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || "").trim().replace(/\/$/, "");
  const serviceRoleKey = (env.SUPABASE_SERVICE_ROLE_KEY || "").trim();
  if (!url || !serviceRoleKey) return null;
  return { url, serviceRoleKey };
}
function mapRow(row) {
  return {
    id: String(row.id),
    email: String(row.email),
    asset: row.asset,
    buy_exchange: row.buy_exchange ?? null,
    sell_exchange: row.sell_exchange ?? null,
    alert_scope: row.alert_scope,
    minimum_net_profit_pct: row.minimum_net_profit_pct === null || row.minimum_net_profit_pct === void 0 ? null : Number(row.minimum_net_profit_pct),
    minimum_net_profit_usd: row.minimum_net_profit_usd === null || row.minimum_net_profit_usd === void 0 ? null : Number(row.minimum_net_profit_usd),
    trade_amount_usd: row.trade_amount_usd === null || row.trade_amount_usd === void 0 ? null : Number(row.trade_amount_usd),
    source_page: String(row.source_page ?? ""),
    source_context: String(row.source_context ?? ""),
    created_at: String(row.created_at),
    updated_at: String(row.updated_at),
    status: row.status,
    unsubscribe_token: String(row.unsubscribe_token),
    consent_version: String(row.consent_version ?? ""),
    user_agent_hash: row.user_agent_hash == null ? null : String(row.user_agent_hash),
    latest_matching_opportunity_at: row.latest_matching_opportunity_at == null ? null : String(row.latest_matching_opportunity_at)
  };
}
function mapDelivery(row) {
  return {
    id: String(row.id),
    alert_id: String(row.alert_id),
    opportunity_fingerprint: String(row.opportunity_fingerprint),
    asset: String(row.asset),
    buy_exchange: String(row.buy_exchange),
    sell_exchange: String(row.sell_exchange),
    estimated_net_profit_pct: row.estimated_net_profit_pct === null || row.estimated_net_profit_pct === void 0 ? null : Number(row.estimated_net_profit_pct),
    estimated_net_profit_usd: row.estimated_net_profit_usd === null || row.estimated_net_profit_usd === void 0 ? null : Number(row.estimated_net_profit_usd),
    opportunity_data_timestamp: row.opportunity_data_timestamp == null ? null : String(row.opportunity_data_timestamp),
    matched_at: String(row.matched_at),
    email_status: row.email_status,
    email_provider: row.email_provider == null ? null : String(row.email_provider),
    provider_message_id: row.provider_message_id == null ? null : String(row.provider_message_id),
    sent_at: row.sent_at == null ? null : String(row.sent_at),
    failure_category: row.failure_category == null ? null : String(row.failure_category),
    created_at: String(row.created_at)
  };
}
async function rest(cfg, path, init = {}) {
  const headers = {
    apikey: cfg.serviceRoleKey,
    Authorization: `Bearer ${cfg.serviceRoleKey}`,
    "Content-Type": "application/json"
  };
  if (init.prefer) headers.Prefer = init.prefer;
  const res = await fetch(`${cfg.url}/rest/v1/${path}`, {
    ...init,
    headers: { ...headers, ...init.headers }
  });
  const text = await res.text();
  let json = null;
  if (text) {
    try {
      json = JSON.parse(text);
    } catch {
      json = null;
    }
  }
  return { status: res.status, json, text };
}
var SupabaseAlertStorage = class _SupabaseAlertStorage {
  constructor(cfg) {
    this.cfg = cfg;
  }
  static fromEnv(env = process.env) {
    const cfg = getConfig(env);
    return cfg ? new _SupabaseAlertStorage(cfg) : null;
  }
  async findByStatus(input, statusFilter) {
    let query = `arbitrage_alerts?select=*&email=eq.${encodeURIComponent(input.email)}&asset=eq.${encodeURIComponent(input.asset)}&alert_scope=eq.${encodeURIComponent(input.alert_scope)}&status=${statusFilter}&limit=20`;
    if (input.alert_scope === "exact_pair") {
      query += `&buy_exchange=eq.${encodeURIComponent(String(input.buy_exchange))}&sell_exchange=eq.${encodeURIComponent(String(input.sell_exchange))}`;
    }
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByStatus failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async findActiveDuplicate(input) {
    return this.findByStatus(input, "in.(pending,active)");
  }
  async findUnsubscribedDuplicate(input) {
    return this.findByStatus(input, "eq.unsubscribed");
  }
  async findByUnsubscribeToken(token) {
    const query = `arbitrage_alerts?select=*&unsubscribe_token=eq.${encodeURIComponent(token)}&limit=1`;
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByToken failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async create(input, meta) {
    const payload = {
      id: meta.id,
      email: input.email,
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      trade_amount_usd: input.trade_amount_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      created_at: meta.now,
      updated_at: meta.now,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      latest_matching_opportunity_at: null
    };
    const { status, json, text } = await rest(
      this.cfg,
      "arbitrage_alerts",
      {
        method: "POST",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`create failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async reactivate(existing, input, meta) {
    const payload = {
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      trade_amount_usd: input.trade_amount_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      updated_at: meta.now
    };
    const { status, json, text } = await rest(
      this.cfg,
      `arbitrage_alerts?id=eq.${encodeURIComponent(existing.id)}`,
      {
        method: "PATCH",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`reactivate failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async markUnsubscribed(token, now) {
    const existing = await this.findByUnsubscribeToken(token);
    if (!existing) return "not_found";
    if (existing.status === "unsubscribed") return "already_unsubscribed";
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alerts?unsubscribe_token=eq.${encodeURIComponent(token)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ status: "unsubscribed", updated_at: now }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`unsubscribe failed (${status}): ${text.slice(0, 120)}`);
    }
    return "unsubscribed";
  }
  async listActiveAlerts(opts) {
    let query = `arbitrage_alerts?select=*&status=eq.active&order=id.asc&limit=${encodeURIComponent(String(opts.limit))}`;
    if (opts.afterId) {
      query += `&id=gt.${encodeURIComponent(opts.afterId)}`;
    }
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`listActiveAlerts failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.map(mapRow);
  }
  async insertDeliveryPending(row) {
    const payload = {
      id: row.id,
      alert_id: row.alert_id,
      opportunity_fingerprint: row.opportunity_fingerprint,
      asset: row.asset,
      buy_exchange: row.buy_exchange,
      sell_exchange: row.sell_exchange,
      estimated_net_profit_pct: row.estimated_net_profit_pct,
      estimated_net_profit_usd: row.estimated_net_profit_usd,
      opportunity_data_timestamp: row.opportunity_data_timestamp,
      matched_at: row.matched_at,
      email_status: "pending",
      email_provider: null,
      provider_message_id: null,
      sent_at: null,
      failure_category: null,
      created_at: row.created_at
    };
    const { status, text } = await rest(this.cfg, "arbitrage_alert_deliveries", {
      method: "POST",
      body: JSON.stringify(payload),
      prefer: "return=minimal"
    });
    if (status === 409) return "duplicate";
    if (status >= 400) {
      throw new StorageFailureError(`insertDeliveryPending failed (${status}): ${text.slice(0, 120)}`);
    }
    return "inserted";
  }
  async getDelivery(alertId, fingerprint) {
    const query = `arbitrage_alert_deliveries?select=*&alert_id=eq.${encodeURIComponent(alertId)}&opportunity_fingerprint=eq.${encodeURIComponent(fingerprint)}&limit=1`;
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`getDelivery failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapDelivery(rows[0]) : null;
  }
  async getLastSentForRoute(alertId, asset, buyExchange, sellExchange) {
    const query = `arbitrage_alert_deliveries?select=*&alert_id=eq.${encodeURIComponent(alertId)}&asset=eq.${encodeURIComponent(asset)}&buy_exchange=eq.${encodeURIComponent(buyExchange)}&sell_exchange=eq.${encodeURIComponent(sellExchange)}&email_status=eq.sent&order=sent_at.desc.nullslast&limit=1`;
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`getLastSentForRoute failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapDelivery(rows[0]) : null;
  }
  async markDeliverySent(id, meta) {
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alert_deliveries?id=eq.${encodeURIComponent(id)}`,
      {
        method: "PATCH",
        body: JSON.stringify({
          email_status: "sent",
          sent_at: meta.sentAt,
          email_provider: meta.provider,
          provider_message_id: meta.providerMessageId,
          failure_category: null
        }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`markDeliverySent failed (${status}): ${text.slice(0, 120)}`);
    }
  }
  async markDeliveryFailed(id, category) {
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alert_deliveries?id=eq.${encodeURIComponent(id)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ email_status: "failed", failure_category: category }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`markDeliveryFailed failed (${status}): ${text.slice(0, 120)}`);
    }
  }
  async markDeliverySkipped(id, category) {
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alert_deliveries?id=eq.${encodeURIComponent(id)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ email_status: "skipped", failure_category: category }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`markDeliverySkipped failed (${status}): ${text.slice(0, 120)}`);
    }
  }
  async updateLatestMatchingOpportunity(alertId, at) {
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alerts?id=eq.${encodeURIComponent(alertId)}`,
      {
        method: "PATCH",
        body: JSON.stringify({
          latest_matching_opportunity_at: at,
          updated_at: at
        }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(
        `updateLatestMatchingOpportunity failed (${status}): ${text.slice(0, 120)}`
      );
    }
  }
};

// src/alerts/match/http.ts
function header(req, name) {
  const raw = req.headers?.[name] ?? req.headers?.[name.toLowerCase()];
  if (Array.isArray(raw)) return raw[0] || "";
  return typeof raw === "string" ? raw : "";
}
function authorizeCronRequest(req, env) {
  const secret = (env.CRON_SECRET || "").trim();
  if (!secret) return "missing_config";
  const auth = header(req, "authorization");
  const expected = `Bearer ${secret}`;
  if (auth !== expected) return "unauthorized";
  return "ok";
}
function readQueryFlag(req, key) {
  const raw = req.query?.[key];
  const v = Array.isArray(raw) ? raw[0] : raw;
  if (v == null) return false;
  const s = String(v).toLowerCase();
  return s === "1" || s === "true" || s === "yes";
}
function readUrlFlag(req, key) {
  const url = req.url;
  if (!url) return false;
  try {
    const u = new URL(url, "http://localhost");
    const s = (u.searchParams.get(key) || "").toLowerCase();
    return s === "1" || s === "true" || s === "yes";
  } catch {
    return false;
  }
}
function isDryRunRequest(req) {
  if (readQueryFlag(req, "dry_run") || readUrlFlag(req, "dry_run")) return true;
  if (req.body && typeof req.body === "object" && !Array.isArray(req.body)) {
    const flag = req.body.dry_run;
    return flag === true || flag === "1" || flag === "true";
  }
  return false;
}
async function handleMatchRequest(req, res, opts = {}) {
  res.setHeader("Cache-Control", "no-store");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  if (req.method === "OPTIONS") {
    res.setHeader("Allow", "GET, POST, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "GET" && req.method !== "POST") {
    res.status(405).json({
      ok: false,
      error: { code: "METHOD_NOT_ALLOWED", message: "Unauthorized." }
    });
    return;
  }
  const env = opts.env ?? process.env;
  const auth = authorizeCronRequest(req, env);
  if (auth === "unauthorized") {
    res.status(401).json({
      ok: false,
      error: { code: "UNAUTHORIZED", message: "Unauthorized." }
    });
    return;
  }
  if (auth === "missing_config") {
    res.status(503).json({
      ok: false,
      error: {
        code: "MISSING_CONFIG",
        message: "Matcher is temporarily unavailable."
      }
    });
    return;
  }
  let storage;
  try {
    if (opts.storage) {
      storage = opts.storage;
    } else {
      const supabase = SupabaseAlertStorage.fromEnv(env);
      if (!supabase) throw new StorageConfigError();
      storage = supabase;
    }
  } catch {
    res.status(503).json({
      ok: false,
      error: {
        code: "MISSING_CONFIG",
        message: "Matcher is temporarily unavailable."
      }
    });
    return;
  }
  const dryRun = isDryRunRequest(req);
  const loaded = opts.snapshot ? { ok: true, snapshot: opts.snapshot, source: "injected" } : await loadSpreadSnapshot({ env });
  if (!loaded.ok) {
    const reason = loaded.reason === "malformed" ? "invalid_snapshot" : "snapshot_unavailable";
    res.status(200).json({
      ok: true,
      dry_run: dryRun,
      skip_reason: reason,
      alerts_checked: 0,
      opportunities_checked: 0,
      matches: 0,
      emails_sent: 0,
      emails_failed: 0,
      duplicates_skipped: 0,
      cooldown_skipped: 0,
      stale_data_skips: 0,
      missing_trade_amount: 0,
      duration_ms: 0
    });
    return;
  }
  const email = opts.email ?? getEmailAdapter(env);
  const summary = await runAlertMatcher({
    storage,
    email,
    snapshot: loaded.snapshot,
    siteOrigin: env.ALERTS_SITE_ORIGIN || "https://coinnavigator.net",
    dryRun,
    ...opts.now ? { now: opts.now } : {},
    ...opts.log ? { log: opts.log } : {}
  });
  res.status(200).json(summary);
}

// src/alerts/vercel/match.ts
async function handler(req, res) {
  await handleMatchRequest(req, res);
}
export {
  handler as default
};
