// Generated by tsup from src/alerts — do not edit by hand.


// src/alerts/rate-limit.ts
var buckets = /* @__PURE__ */ new Map();
function checkRateLimit(key, limit = 10, windowMs = 60 * 60 * 1e3, now = Date.now()) {
  const existing = buckets.get(key);
  if (!existing || now >= existing.resetAt) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { allowed: true, retryAfterSec: 0 };
  }
  if (existing.count >= limit) {
    return {
      allowed: false,
      retryAfterSec: Math.max(1, Math.ceil((existing.resetAt - now) / 1e3))
    };
  }
  existing.count += 1;
  return { allowed: true, retryAfterSec: 0 };
}

// src/alerts/storage.ts
var StorageConfigError = class extends Error {
  constructor(message = "Alert storage is not configured") {
    super(message);
    this.name = "StorageConfigError";
  }
};
var StorageFailureError = class extends Error {
  constructor(message = "Alert storage failed") {
    super(message);
    this.name = "StorageFailureError";
  }
};

// src/alerts/tokens.ts
import { createHash, randomBytes } from "crypto";

// src/alerts/allowlist.ts
var SUPPORTED_EXCHANGES = [
  "Binance",
  "MEXC",
  "Bybit",
  "OKX",
  "KuCoin",
  "Gate"
];
var SUPPORTED_ASSETS = [
  "BTC",
  "ETH",
  "SOL",
  "XRP",
  "TON",
  "DOGE",
  "ADA",
  "BNB",
  "TRX",
  "DOT",
  "LINK",
  "LTC",
  "AVAX",
  "MATIC",
  "SHIB",
  "UNI",
  "XLM",
  "NEAR",
  "ATOM",
  "APT"
];
var EXCHANGE_SET = new Set(SUPPORTED_EXCHANGES);
var ASSET_SET = new Set(SUPPORTED_ASSETS);

// src/alerts/validate.ts
function validateUnsubscribeToken(raw) {
  if (typeof raw !== "string") return null;
  const token = raw.trim();
  if (!/^[a-f0-9]{64}$/i.test(token)) return null;
  return token.toLowerCase();
}

// src/alerts/service.ts
async function unsubscribeAlert(tokenRaw, storage, now = () => (/* @__PURE__ */ new Date()).toISOString()) {
  const token = validateUnsubscribeToken(tokenRaw);
  if (!token) {
    return {
      response: {
        ok: false,
        error: {
          code: "VALIDATION_ERROR",
          message: "Please check the submitted details."
        }
      },
      httpStatus: 400
    };
  }
  try {
    const result = await storage.markUnsubscribed(token, now());
    if (result === "not_found") {
      return {
        response: {
          ok: false,
          error: { code: "NOT_FOUND", message: "This unsubscribe link is not valid." }
        },
        httpStatus: 404
      };
    }
    return {
      response: {
        ok: true,
        status: result === "already_unsubscribed" ? "already_unsubscribed" : "unsubscribed"
      },
      httpStatus: 200
    };
  } catch (err) {
    if (err instanceof StorageConfigError) {
      return {
        response: {
          ok: false,
          error: {
            code: "MISSING_CONFIG",
            message: "Alert storage is temporarily unavailable."
          }
        },
        httpStatus: 503
      };
    }
    return {
      response: {
        ok: false,
        error: {
          code: "SERVER_ERROR",
          message: "Unable to process unsubscribe right now."
        }
      },
      httpStatus: 503
    };
  }
}

// src/alerts/supabase-storage.ts
function getConfig(env = process.env) {
  const url = (env.SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL || "").trim().replace(/\/$/, "");
  const serviceRoleKey = (env.SUPABASE_SERVICE_ROLE_KEY || "").trim();
  if (!url || !serviceRoleKey) return null;
  return { url, serviceRoleKey };
}
function mapRow(row) {
  return {
    id: String(row.id),
    email: String(row.email),
    asset: row.asset,
    buy_exchange: row.buy_exchange ?? null,
    sell_exchange: row.sell_exchange ?? null,
    alert_scope: row.alert_scope,
    minimum_net_profit_pct: row.minimum_net_profit_pct === null || row.minimum_net_profit_pct === void 0 ? null : Number(row.minimum_net_profit_pct),
    minimum_net_profit_usd: row.minimum_net_profit_usd === null || row.minimum_net_profit_usd === void 0 ? null : Number(row.minimum_net_profit_usd),
    source_page: String(row.source_page ?? ""),
    source_context: String(row.source_context ?? ""),
    created_at: String(row.created_at),
    updated_at: String(row.updated_at),
    status: row.status,
    unsubscribe_token: String(row.unsubscribe_token),
    consent_version: String(row.consent_version ?? ""),
    user_agent_hash: row.user_agent_hash == null ? null : String(row.user_agent_hash),
    latest_matching_opportunity_at: row.latest_matching_opportunity_at == null ? null : String(row.latest_matching_opportunity_at)
  };
}
async function rest(cfg, path, init = {}) {
  const headers = {
    apikey: cfg.serviceRoleKey,
    Authorization: `Bearer ${cfg.serviceRoleKey}`,
    "Content-Type": "application/json"
  };
  if (init.prefer) headers.Prefer = init.prefer;
  const res = await fetch(`${cfg.url}/rest/v1/${path}`, {
    ...init,
    headers: { ...headers, ...init.headers }
  });
  const text = await res.text();
  let json = null;
  if (text) {
    try {
      json = JSON.parse(text);
    } catch {
      json = null;
    }
  }
  return { status: res.status, json, text };
}
var SupabaseAlertStorage = class _SupabaseAlertStorage {
  constructor(cfg) {
    this.cfg = cfg;
  }
  static fromEnv(env = process.env) {
    const cfg = getConfig(env);
    return cfg ? new _SupabaseAlertStorage(cfg) : null;
  }
  async findByStatus(input, statusFilter) {
    let query = `arbitrage_alerts?select=*&email=eq.${encodeURIComponent(input.email)}&asset=eq.${encodeURIComponent(input.asset)}&alert_scope=eq.${encodeURIComponent(input.alert_scope)}&status=${statusFilter}&limit=20`;
    if (input.alert_scope === "exact_pair") {
      query += `&buy_exchange=eq.${encodeURIComponent(String(input.buy_exchange))}&sell_exchange=eq.${encodeURIComponent(String(input.sell_exchange))}`;
    }
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByStatus failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async findActiveDuplicate(input) {
    return this.findByStatus(input, "in.(pending,active)");
  }
  async findUnsubscribedDuplicate(input) {
    return this.findByStatus(input, "eq.unsubscribed");
  }
  async findByUnsubscribeToken(token) {
    const query = `arbitrage_alerts?select=*&unsubscribe_token=eq.${encodeURIComponent(token)}&limit=1`;
    const { status, json, text } = await rest(this.cfg, query, {
      method: "GET"
    });
    if (status >= 400) {
      throw new StorageFailureError(`findByToken failed (${status}): ${text.slice(0, 120)}`);
    }
    const rows = Array.isArray(json) ? json : [];
    return rows.length ? mapRow(rows[0]) : null;
  }
  async create(input, meta) {
    const payload = {
      id: meta.id,
      email: input.email,
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      created_at: meta.now,
      updated_at: meta.now,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      latest_matching_opportunity_at: null
    };
    const { status, json, text } = await rest(
      this.cfg,
      "arbitrage_alerts",
      {
        method: "POST",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`create failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async reactivate(existing, input, meta) {
    const payload = {
      asset: input.asset,
      buy_exchange: input.buy_exchange,
      sell_exchange: input.sell_exchange,
      alert_scope: input.alert_scope,
      minimum_net_profit_pct: input.minimum_net_profit_pct,
      minimum_net_profit_usd: input.minimum_net_profit_usd,
      source_page: input.source_page,
      source_context: input.source_context,
      consent_version: input.consent_version,
      user_agent_hash: input.user_agent_hash,
      status: "active",
      unsubscribe_token: meta.unsubscribe_token,
      updated_at: meta.now
    };
    const { status, json, text } = await rest(
      this.cfg,
      `arbitrage_alerts?id=eq.${encodeURIComponent(existing.id)}`,
      {
        method: "PATCH",
        body: JSON.stringify(payload),
        prefer: "return=representation"
      }
    );
    if (status >= 400 || !Array.isArray(json) || !json[0]) {
      throw new StorageFailureError(`reactivate failed (${status}): ${text.slice(0, 120)}`);
    }
    return mapRow(json[0]);
  }
  async markUnsubscribed(token, now) {
    const existing = await this.findByUnsubscribeToken(token);
    if (!existing) return "not_found";
    if (existing.status === "unsubscribed") return "already_unsubscribed";
    const { status, text } = await rest(
      this.cfg,
      `arbitrage_alerts?unsubscribe_token=eq.${encodeURIComponent(token)}`,
      {
        method: "PATCH",
        body: JSON.stringify({ status: "unsubscribed", updated_at: now }),
        prefer: "return=minimal"
      }
    );
    if (status >= 400) {
      throw new StorageFailureError(`unsubscribe failed (${status}): ${text.slice(0, 120)}`);
    }
    return "unsubscribed";
  }
};

// src/alerts/http.ts
var MAX_BODY_BYTES = 8 * 1024;
function header(req, name) {
  const raw = req.headers?.[name] ?? req.headers?.[name.toLowerCase()];
  if (Array.isArray(raw)) return raw[0] || "";
  return typeof raw === "string" ? raw : "";
}
function clientIp(req) {
  const fwd = header(req, "x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim().slice(0, 64);
  const real = header(req, "x-real-ip");
  if (real) return real.trim().slice(0, 64);
  return (req.socket?.remoteAddress || "unknown").slice(0, 64);
}
function readBody(req) {
  if (req.body == null) {
    return {
      ok: false,
      status: 400,
      response: {
        ok: false,
        error: { code: "VALIDATION_ERROR", message: "Please check the submitted details." }
      }
    };
  }
  if (typeof req.body === "string") {
    if (req.body.length > MAX_BODY_BYTES) {
      return {
        ok: false,
        status: 413,
        response: {
          ok: false,
          error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the submitted details." }
        }
      };
    }
    try {
      return { ok: true, value: JSON.parse(req.body) };
    } catch {
      return {
        ok: false,
        status: 400,
        response: {
          ok: false,
          error: { code: "VALIDATION_ERROR", message: "Please check the submitted details." }
        }
      };
    }
  }
  const encoded = JSON.stringify(req.body);
  if (encoded.length > MAX_BODY_BYTES) {
    return {
      ok: false,
      status: 413,
      response: {
        ok: false,
        error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the submitted details." }
      }
    };
  }
  return { ok: true, value: req.body };
}
function resolveStorage(env, injected) {
  if (injected) return injected;
  const supabase = SupabaseAlertStorage.fromEnv(env);
  if (supabase) return supabase;
  throw new StorageConfigError();
}
function unsubscribeHtml(ok, message) {
  const title = ok ? "Unsubscribed" : "Unsubscribe";
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="robots" content="noindex,nofollow" />
  <title>${title} | CoinNavigator</title>
  <style>
    body{font-family:Inter,system-ui,sans-serif;background:#0b0f1a;color:#f8fafc;display:flex;min-height:100vh;align-items:center;justify-content:center;margin:0;padding:1.5rem}
    .card{max-width:420px;background:#161b2a;border:1px solid #2d334a;border-radius:18px;padding:1.5rem}
    h1{font-size:1.35rem;margin:0 0 .75rem}
    p{color:#94a3b8;line-height:1.5;margin:0 0 1rem}
    a{color:#818cf8;font-weight:700;text-decoration:none}
  </style>
</head>
<body>
  <div class="card">
    <h1>${title}</h1>
    <p>${message}</p>
    <p><a href="/">Back to CoinNavigator</a></p>
  </div>
</body>
</html>`;
}
async function handleUnsubscribeRequest(req, res, opts = {}) {
  res.setHeader("Cache-Control", "no-store");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  if (req.method === "OPTIONS") {
    res.setHeader("Allow", "GET, POST, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "GET" && req.method !== "POST") {
    res.status(405).json({
      ok: false,
      error: { code: "METHOD_NOT_ALLOWED", message: "Please check the submitted details." }
    });
    return;
  }
  const ip = clientIp(req);
  const rl = checkRateLimit(`alerts:unsub:${ip}`, 30);
  if (!rl.allowed) {
    res.setHeader("Retry-After", String(rl.retryAfterSec));
    res.status(429).json({
      ok: false,
      error: { code: "RATE_LIMITED", message: "Too many requests. Please try again later." }
    });
    return;
  }
  let token = req.query?.token;
  if (Array.isArray(token)) token = token[0];
  if (!token && req.method === "POST") {
    const body = readBody(req);
    if (body.ok && body.value && typeof body.value === "object") {
      token = body.value.token;
    }
  }
  const env = opts.env ?? process.env;
  let storage;
  try {
    storage = resolveStorage(env, opts.storage);
  } catch {
    const accept2 = header(req, "accept");
    if (req.method === "GET" && accept2.includes("text/html")) {
      res.setHeader("Content-Type", "text/html; charset=utf-8");
      res.status(503).send(unsubscribeHtml(false, "Alert storage is temporarily unavailable."));
      return;
    }
    res.status(503).json({
      ok: false,
      error: { code: "MISSING_CONFIG", message: "Alert storage is temporarily unavailable." }
    });
    return;
  }
  const result = await unsubscribeAlert(token, storage);
  const accept = header(req, "accept");
  const wantsHtml = req.method === "GET" && accept.includes("text/html");
  if (wantsHtml) {
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    if (result.response.ok) {
      res.status(200).send(
        unsubscribeHtml(
          true,
          "You have been unsubscribed from CoinNavigator opportunity alerts. You will no longer receive these emails."
        )
      );
      return;
    }
    res.status(result.httpStatus).send(unsubscribeHtml(false, result.response.error.message));
    return;
  }
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.status(result.httpStatus).json(result.response);
}

// src/alerts/vercel/unsubscribe.ts
async function handler(req, res) {
  await handleUnsubscribeRequest(req, res);
}
export {
  handler as default
};
