// Generated by tsup from src/route-validator — do not edit by hand.


// src/alerts/rate-limit.ts
var buckets = /* @__PURE__ */ new Map();
function checkRateLimit(key, limit = 10, windowMs = 60 * 60 * 1e3, now = Date.now()) {
  const existing = buckets.get(key);
  if (!existing || now >= existing.resetAt) {
    buckets.set(key, { count: 1, resetAt: now + windowMs });
    return { allowed: true, retryAfterSec: 0 };
  }
  if (existing.count >= limit) {
    return {
      allowed: false,
      retryAfterSec: Math.max(1, Math.ceil((existing.resetAt - now) / 1e3))
    };
  }
  existing.count += 1;
  return { allowed: true, retryAfterSec: 0 };
}

// src/net-profit/config.ts
var NET_PROFIT_THRESHOLDS = {
  marginalProfitUsd: 1,
  marginalProfitPct: 0.05,
  costDominanceRatio: 0.7
};
var EXCHANGE_FEE_ESTIMATES = {
  Binance: {
    id: "Binance",
    displayName: "Binance",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.binance.com/en/fee/schedule",
    sourceNote: "Default spot VIP0 schedule (estimate). BNB discounts not applied.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Binance"
  },
  MEXC: {
    id: "MEXC",
    displayName: "MEXC",
    estimatedSpotMakerFeePct: 0,
    estimatedSpotTakerFeePct: 0.05,
    sourceUrl: "https://www.mexc.com/fee",
    sourceNote: "Default spot schedule (estimate). Maker often 0%; taker ~0.05%.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "MEXC"
  },
  Bybit: {
    id: "Bybit",
    displayName: "Bybit",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.bybit.com/en/help-center/article/Trading-Fee-Structure",
    sourceNote: "Default spot VIP0 schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Bybit"
  },
  OKX: {
    id: "OKX",
    displayName: "OKX",
    estimatedSpotMakerFeePct: 0.08,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.okx.com/fees",
    sourceNote: "Default spot VIP0 schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "OKX"
  },
  KuCoin: {
    id: "KuCoin",
    displayName: "KuCoin",
    estimatedSpotMakerFeePct: 0.1,
    estimatedSpotTakerFeePct: 0.1,
    sourceUrl: "https://www.kucoin.com/rate",
    sourceNote: "Default spot schedule (estimate).",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "KuCoin"
  },
  Gate: {
    id: "Gate",
    displayName: "Gate.io",
    estimatedSpotMakerFeePct: 0.2,
    estimatedSpotTakerFeePct: 0.2,
    sourceUrl: "https://www.gate.io/fee",
    sourceNote: "Default spot schedule (estimate). Higher than peers on many pairs.",
    lastVerified: "2026-07-27",
    isEstimated: true,
    affiliateKey: "Gate"
  }
};
var SUPPORTED_EXCHANGES = Object.freeze(
  Object.keys(EXCHANGE_FEE_ESTIMATES)
);
function getExchangeFeeEstimate(exchange) {
  if (Object.prototype.hasOwnProperty.call(EXCHANGE_FEE_ESTIMATES, exchange)) {
    return EXCHANGE_FEE_ESTIMATES[exchange];
  }
  return void 0;
}
function getEstimatedTakerFeePct(exchange) {
  const row = getExchangeFeeEstimate(exchange);
  return row ? row.estimatedSpotTakerFeePct : null;
}

// src/net-profit/validate.ts
import Decimal from "decimal.js";
Decimal.set({
  precision: 28,
  rounding: Decimal.ROUND_HALF_UP
});
function d(value) {
  return new Decimal(value);
}
function toNumber(value) {
  return value.toNumber();
}
function isFiniteNumber(value) {
  return typeof value === "number" && Number.isFinite(value);
}
function validateNetProfitInput(input) {
  const issues = [];
  function requireFinite(field, value) {
    if (!isFiniteNumber(value)) {
      issues.push({ field, message: `${field} must be a finite number` });
    }
  }
  function requirePositive(field, value) {
    if (!(value > 0)) {
      issues.push({ field, message: `${field} must be greater than zero` });
    }
  }
  function requireNonNegative(field, value) {
    if (value < 0) {
      issues.push({ field, message: `${field} must be >= 0` });
    }
  }
  requireFinite("investmentUsd", input.investmentUsd);
  requireFinite("buyPrice", input.buyPrice);
  requireFinite("sellPrice", input.sellPrice);
  requireFinite("buyTradingFeePct", input.buyTradingFeePct);
  requireFinite("sellTradingFeePct", input.sellTradingFeePct);
  requireFinite("withdrawalFeeAsset", input.withdrawalFeeAsset);
  requireFinite("buySlippagePct", input.buySlippagePct);
  requireFinite("sellSlippagePct", input.sellSlippagePct);
  if (issues.length > 0) return issues;
  requirePositive("investmentUsd", input.investmentUsd);
  requirePositive("buyPrice", input.buyPrice);
  requirePositive("sellPrice", input.sellPrice);
  requireNonNegative("buyTradingFeePct", input.buyTradingFeePct);
  requireNonNegative("sellTradingFeePct", input.sellTradingFeePct);
  requireNonNegative("withdrawalFeeAsset", input.withdrawalFeeAsset);
  requireNonNegative("buySlippagePct", input.buySlippagePct);
  requireNonNegative("sellSlippagePct", input.sellSlippagePct);
  if (typeof input.assetSymbol !== "string" || input.assetSymbol.trim() === "") {
    issues.push({ field: "assetSymbol", message: "assetSymbol is required" });
  }
  if (typeof input.buyExchange !== "string" || input.buyExchange.trim() === "") {
    issues.push({ field: "buyExchange", message: "buyExchange is required" });
  }
  if (typeof input.sellExchange !== "string" || input.sellExchange.trim() === "") {
    issues.push({ field: "sellExchange", message: "sellExchange is required" });
  }
  if (input.networkFeeAsset !== void 0) {
    if (!isFiniteNumber(input.networkFeeAsset)) {
      issues.push({ field: "networkFeeAsset", message: "networkFeeAsset must be a finite number" });
    } else if (input.networkFeeAsset < 0) {
      issues.push({ field: "networkFeeAsset", message: "networkFeeAsset must be >= 0" });
    }
  }
  if (input.additionalCostUsd !== void 0) {
    if (!isFiniteNumber(input.additionalCostUsd)) {
      issues.push({ field: "additionalCostUsd", message: "additionalCostUsd must be a finite number" });
    } else if (input.additionalCostUsd < 0) {
      issues.push({ field: "additionalCostUsd", message: "additionalCostUsd must be >= 0" });
    }
  }
  return issues;
}

// src/net-profit/calculate.ts
function invalidResult(warnings) {
  return {
    purchasedQty: 0,
    sellableQty: 0,
    grossSpreadPct: 0,
    grossProfitUsd: 0,
    buyTradingFeeUsd: 0,
    sellTradingFeeUsd: 0,
    withdrawalCostAsset: 0,
    withdrawalCostUsd: 0,
    networkCostUsd: 0,
    estimatedSlippageCostUsd: 0,
    additionalCostUsd: 0,
    totalEstimatedCostsUsd: 0,
    netProceedsUsd: 0,
    estimatedNetProfitUsd: 0,
    netProfitPct: 0,
    breakEvenSpreadPct: 0,
    verdict: "invalid",
    warnings
  };
}
function roundMoney(value) {
  return toNumber(value.toDecimalPlaces(8, Decimal.ROUND_HALF_UP));
}
function roundPct(value) {
  return toNumber(value.toDecimalPlaces(8, Decimal.ROUND_HALF_UP));
}
function calculateNetProfit(input) {
  const issues = validateNetProfitInput(input);
  if (issues.length > 0) {
    return invalidResult(issues.map((i) => i.message));
  }
  const warnings = [];
  const investment = d(input.investmentUsd);
  const buyPrice = d(input.buyPrice);
  const sellPrice = d(input.sellPrice);
  const buyFeePct = d(input.buyTradingFeePct).div(100);
  const sellFeePct = d(input.sellTradingFeePct).div(100);
  const buySlipPct = d(input.buySlippagePct).div(100);
  const sellSlipPct = d(input.sellSlippagePct).div(100);
  const withdrawalAsset = d(input.withdrawalFeeAsset);
  const networkAsset = d(input.networkFeeAsset ?? 0);
  const additionalUsd = d(input.additionalCostUsd ?? 0);
  if (buyPrice.eq(sellPrice)) {
    warnings.push("Buy and sell prices are identical \u2014 gross spread is zero.");
  }
  const grossSpreadPct = sellPrice.minus(buyPrice).div(buyPrice).mul(100);
  const grossProfitUsd = investment.mul(sellPrice.minus(buyPrice)).div(buyPrice);
  const effectiveBuyPrice = buyPrice.mul(d(1).plus(buySlipPct));
  const effectiveSellPrice = sellPrice.mul(d(1).minus(sellSlipPct));
  if (effectiveSellPrice.lte(0)) {
    return invalidResult(["Sell slippage reduces effective sell price to zero or below."]);
  }
  const purchasedQty = investment.div(effectiveBuyPrice);
  const sellableQty = purchasedQty.minus(withdrawalAsset).minus(networkAsset);
  if (sellableQty.lte(0)) {
    warnings.push(
      "Withdrawal + network fees in asset units meet or exceed the purchased quantity."
    );
    return {
      ...invalidResult(warnings),
      purchasedQty: roundMoney(purchasedQty),
      sellableQty: 0,
      additionalCostUsd: roundMoney(additionalUsd),
      grossSpreadPct: roundPct(grossSpreadPct),
      grossProfitUsd: roundMoney(grossProfitUsd),
      withdrawalCostAsset: roundMoney(withdrawalAsset),
      withdrawalCostUsd: roundMoney(withdrawalAsset.mul(effectiveSellPrice)),
      networkCostUsd: roundMoney(networkAsset.mul(effectiveSellPrice)),
      verdict: "invalid"
    };
  }
  const buyTradingFeeUsd = investment.mul(buyFeePct);
  const sellNotionalUsd = sellableQty.mul(effectiveSellPrice);
  const sellTradingFeeUsd = sellNotionalUsd.mul(sellFeePct);
  const withdrawalCostUsd = withdrawalAsset.mul(effectiveSellPrice);
  const networkCostUsd = networkAsset.mul(effectiveSellPrice);
  const idealQty = investment.div(buyPrice);
  const idealSellable = Decimal.max(idealQty.minus(withdrawalAsset).minus(networkAsset), 0);
  const idealProceeds = idealSellable.mul(sellPrice);
  const slippedProceeds = sellableQty.mul(effectiveSellPrice);
  const estimatedSlippageCostUsd = Decimal.max(idealProceeds.minus(slippedProceeds), 0);
  const totalEstimatedCostsUsd = buyTradingFeeUsd.plus(sellTradingFeeUsd).plus(withdrawalCostUsd).plus(networkCostUsd).plus(estimatedSlippageCostUsd).plus(additionalUsd);
  const netProceedsUsd = sellNotionalUsd.minus(sellTradingFeeUsd);
  const estimatedNetProfitUsd = netProceedsUsd.minus(investment).minus(buyTradingFeeUsd).minus(additionalUsd);
  const netProfitPct = estimatedNetProfitUsd.div(investment).mul(100);
  const breakEvenSpreadPct = totalEstimatedCostsUsd.div(investment).mul(100);
  if (grossProfitUsd.gt(0) && totalEstimatedCostsUsd.div(grossProfitUsd).gte(NET_PROFIT_THRESHOLDS.costDominanceRatio)) {
    warnings.push(
      `Estimated costs consume \u2265 ${NET_PROFIT_THRESHOLDS.costDominanceRatio * 100}% of gross spread profit.`
    );
  }
  if (estimatedSlippageCostUsd.gte(grossProfitUsd) && grossProfitUsd.gt(0)) {
    warnings.push("Estimated slippage alone consumes the full gross spread profit.");
  }
  if (input.buyExchange === input.sellExchange) {
    warnings.push("Buy and sell exchanges are the same \u2014 this is not a cross-exchange arb.");
  }
  let verdict;
  if (estimatedNetProfitUsd.lte(0)) {
    verdict = "not_profitable";
  } else if (estimatedNetProfitUsd.lt(NET_PROFIT_THRESHOLDS.marginalProfitUsd) || netProfitPct.lt(NET_PROFIT_THRESHOLDS.marginalProfitPct)) {
    verdict = "marginal";
    warnings.push(
      `Net profit is below the safety threshold ($${NET_PROFIT_THRESHOLDS.marginalProfitUsd} or ${NET_PROFIT_THRESHOLDS.marginalProfitPct}%).`
    );
  } else {
    verdict = "profitable";
  }
  return {
    purchasedQty: roundMoney(purchasedQty),
    sellableQty: roundMoney(sellableQty),
    grossSpreadPct: roundPct(grossSpreadPct),
    grossProfitUsd: roundMoney(grossProfitUsd),
    buyTradingFeeUsd: roundMoney(buyTradingFeeUsd),
    sellTradingFeeUsd: roundMoney(sellTradingFeeUsd),
    withdrawalCostAsset: roundMoney(withdrawalAsset),
    withdrawalCostUsd: roundMoney(withdrawalCostUsd),
    networkCostUsd: roundMoney(networkCostUsd),
    estimatedSlippageCostUsd: roundMoney(estimatedSlippageCostUsd),
    additionalCostUsd: roundMoney(additionalUsd),
    totalEstimatedCostsUsd: roundMoney(totalEstimatedCostsUsd),
    netProceedsUsd: roundMoney(netProceedsUsd),
    estimatedNetProfitUsd: roundMoney(estimatedNetProfitUsd),
    netProfitPct: roundPct(netProfitPct),
    breakEvenSpreadPct: roundPct(breakEvenSpreadPct),
    verdict,
    warnings
  };
}

// src/route-validator/symbols.ts
var VALIDATOR_EXCHANGES = ["Binance", "Bybit", "MEXC"];
var VALIDATOR_ASSETS = ["BTC", "ETH", "SOL", "XRP"];
var EXCHANGE_SET = new Set(VALIDATOR_EXCHANGES);
var ASSET_SET = new Set(VALIDATOR_ASSETS);
var EXCHANGE_ALIASES = {
  binance: "Binance",
  bybit: "Bybit",
  mexc: "MEXC"
};
var SYMBOL_MAP = {
  Binance: {
    BTC: "BTCUSDT",
    ETH: "ETHUSDT",
    SOL: "SOLUSDT",
    XRP: "XRPUSDT"
  },
  Bybit: {
    BTC: "BTCUSDT",
    ETH: "ETHUSDT",
    SOL: "SOLUSDT",
    XRP: "XRPUSDT"
  },
  MEXC: {
    BTC: "BTCUSDT",
    ETH: "ETHUSDT",
    SOL: "SOLUSDT",
    XRP: "XRPUSDT"
  }
};
function normalizeValidatorExchange(raw) {
  if (typeof raw !== "string") return null;
  const t = raw.trim();
  if (EXCHANGE_SET.has(t)) return t;
  return EXCHANGE_ALIASES[t.toLowerCase()] ?? null;
}
function normalizeValidatorAsset(raw) {
  if (typeof raw !== "string") return null;
  let s = raw.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
  if (!s) return null;
  if (s.endsWith("USDT") && s.length > 4) s = s.slice(0, -4);
  if (s === "USDT") return "USDT";
  if (ASSET_SET.has(s)) return s;
  return null;
}
function resolveSymbol(exchange, asset) {
  return SYMBOL_MAP[exchange][asset];
}
var MIN_TRADE_USD = 10;
var MAX_TRADE_USD = 1e5;
var ORDER_BOOK_LIMIT = 50;
var UPSTREAM_TIMEOUT_MS = 6e3;
var RESULT_TTL_SECONDS = 8;
var STALE_BOOK_MS = 15e3;

// src/route-validator/adapters/base.ts
var UpstreamError = class extends Error {
  constructor(message, category) {
    super(message);
    this.category = category;
    this.name = "UpstreamError";
  }
};
async function fetchJson(url, opts = {}) {
  const timeoutMs = opts.timeoutMs ?? UPSTREAM_TIMEOUT_MS;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "application/json",
        ...opts.headers ?? {}
      },
      signal: controller.signal
    });
    if (res.status === 429) {
      throw new UpstreamError("rate_limited", "rate_limit");
    }
    if (!res.ok) {
      throw new UpstreamError(`http_${res.status}`, "http");
    }
    return await res.json();
  } catch (err) {
    if (err instanceof UpstreamError) throw err;
    if (err instanceof Error && err.name === "AbortError") {
      throw new UpstreamError("timeout", "timeout");
    }
    throw new UpstreamError("unavailable", "unavailable");
  } finally {
    clearTimeout(timer);
  }
}
function normalizeLevels(raw) {
  if (!Array.isArray(raw)) throw new UpstreamError("malformed_levels", "malformed");
  const out = [];
  for (const row of raw) {
    if (!Array.isArray(row) || row.length < 2) {
      throw new UpstreamError("malformed_level", "malformed");
    }
    const price = String(row[0]);
    const quantity = String(row[1]);
    if (!price || !quantity) throw new UpstreamError("malformed_level", "malformed");
    out.push({ price, quantity });
  }
  return out.slice(0, ORDER_BOOK_LIMIT);
}

// src/route-validator/adapters/binance.ts
var binanceAdapter = {
  exchange: "Binance",
  async fetchOrderBook(symbol) {
    const url = `https://api.binance.com/api/v3/depth?symbol=${encodeURIComponent(symbol)}&limit=${ORDER_BOOK_LIMIT}`;
    const json = await fetchJson(url);
    if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
    const body = json;
    const bids = normalizeLevels(body.bids);
    const asks = normalizeLevels(body.asks);
    if (!bids.length || !asks.length) throw new UpstreamError("empty_book", "malformed");
    return {
      exchange: "Binance",
      symbol,
      bids,
      asks,
      exchangeTimestampMs: null,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  },
  // Binance capital config requires API key — not available for this MVP.
  async fetchTransferMeta() {
    return null;
  }
};

// src/route-validator/adapters/bybit.ts
var bybitAdapter = {
  exchange: "Bybit",
  async fetchOrderBook(symbol) {
    const url = `https://api.bybit.com/v5/market/orderbook?category=spot&symbol=${encodeURIComponent(symbol)}&limit=${ORDER_BOOK_LIMIT}`;
    const json = await fetchJson(url);
    if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
    const body = json;
    if (body.retCode !== 0 || !body.result) {
      throw new UpstreamError("bybit_error", "unavailable");
    }
    const bids = normalizeLevels(body.result.b);
    const asks = normalizeLevels(body.result.a);
    if (!bids.length || !asks.length) throw new UpstreamError("empty_book", "malformed");
    const ts = body.result.ts != null ? Number(body.result.ts) : null;
    return {
      exchange: "Bybit",
      symbol,
      bids,
      asks,
      exchangeTimestampMs: Number.isFinite(ts) ? ts : null,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  },
  async fetchTransferMeta() {
    return null;
  }
};

// src/route-validator/adapters/mexc.ts
var mexcAdapter = {
  exchange: "MEXC",
  async fetchOrderBook(symbol) {
    const url = `https://api.mexc.com/api/v3/depth?symbol=${encodeURIComponent(symbol)}&limit=${ORDER_BOOK_LIMIT}`;
    const json = await fetchJson(url);
    if (!json || typeof json !== "object") throw new UpstreamError("malformed", "malformed");
    const body = json;
    const bids = normalizeLevels(body.bids);
    const asks = normalizeLevels(body.asks);
    if (!bids.length || !asks.length) throw new UpstreamError("empty_book", "malformed");
    const ts = body.timestamp != null ? Number(body.timestamp) : null;
    return {
      exchange: "MEXC",
      symbol,
      bids,
      asks,
      exchangeTimestampMs: Number.isFinite(ts) ? ts : null,
      fetchedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  },
  async fetchTransferMeta() {
    return null;
  }
};

// src/route-validator/adapters/index.ts
var ADAPTERS = {
  Binance: binanceAdapter,
  Bybit: bybitAdapter,
  MEXC: mexcAdapter
};
function getAdapter(exchange) {
  const adapter = ADAPTERS[exchange];
  if (!adapter) throw new UpstreamError("unsupported_exchange", "unsupported");
  return adapter;
}

// src/route-validator/cache.ts
var store = /* @__PURE__ */ new Map();
function cacheGet(key, now = Date.now()) {
  const hit = store.get(key);
  if (!hit) return null;
  if (now >= hit.expiresAt) {
    store.delete(key);
    return null;
  }
  return hit.value;
}
function cacheSet(key, value, ttlMs, now = Date.now()) {
  store.set(key, { value, expiresAt: now + ttlMs });
  if (store.size > 200) {
    for (const [k, v] of store) {
      if (now >= v.expiresAt) store.delete(k);
    }
  }
}

// src/route-validator/order-book.ts
import Decimal2 from "decimal.js";
Decimal2.set({ precision: 28, rounding: Decimal2.ROUND_HALF_UP });
function d2(n) {
  return new Decimal2(n);
}
function toNum(x) {
  return x.toNumber();
}
function parseLevels(levels) {
  const out = [];
  for (const lvl of levels) {
    const price = d2(lvl.price);
    const qty = d2(lvl.quantity);
    if (!price.isFinite() || !qty.isFinite() || price.lte(0) || qty.lte(0)) {
      throw new Error("invalid_order_book_level");
    }
    out.push({ price, qty });
  }
  return out;
}
function simulateBuyFromAsks(asks, tradeAmountUsd) {
  if (!asks.length) throw new Error("empty_asks");
  if (!Number.isFinite(tradeAmountUsd) || tradeAmountUsd <= 0) {
    throw new Error("invalid_trade_amount");
  }
  const levels = parseLevels(asks);
  levels.sort((a, b) => a.price.comparedTo(b.price));
  const bestAsk = levels[0].price;
  let remaining = d2(tradeAmountUsd);
  let acquired = d2(0);
  let spent = d2(0);
  let levelsUsed = 0;
  let depth = d2(0);
  for (const lvl of levels) {
    depth = depth.plus(lvl.price.mul(lvl.qty));
    if (remaining.lte(0)) continue;
    const levelNotional = lvl.price.mul(lvl.qty);
    const takeNotional = Decimal2.min(remaining, levelNotional);
    const takeQty = takeNotional.div(lvl.price);
    acquired = acquired.plus(takeQty);
    spent = spent.plus(takeNotional);
    remaining = remaining.minus(takeNotional);
    levelsUsed += 1;
  }
  const fullyFillable = remaining.lte(0) || remaining.div(tradeAmountUsd).lt(1e-4);
  const avg = acquired.gt(0) ? spent.div(acquired) : null;
  const slip = avg && bestAsk.gt(0) ? avg.minus(bestAsk).div(bestAsk).mul(100) : null;
  return {
    fullyFillable,
    assetQuantity: toNum(acquired.toDecimalPlaces(12)),
    quoteSpentUsd: toNum(spent.toDecimalPlaces(8)),
    averageExecutionPrice: avg ? toNum(avg.toDecimalPlaces(12)) : null,
    bestAsk: toNum(bestAsk),
    estimatedSlippagePct: slip ? toNum(slip.toDecimalPlaces(6)) : null,
    availableDepthUsd: toNum(depth.toDecimalPlaces(2)),
    unfilledQuoteUsd: toNum(Decimal2.max(0, remaining).toDecimalPlaces(8)),
    levelsUsed
  };
}
function simulateSellFromBids(bids, assetQty) {
  if (!bids.length) throw new Error("empty_bids");
  if (!Number.isFinite(assetQty) || assetQty <= 0) {
    throw new Error("invalid_asset_qty");
  }
  const levels = parseLevels(bids);
  levels.sort((a, b) => b.price.comparedTo(a.price));
  const bestBid = levels[0].price;
  let remaining = d2(assetQty);
  let sold = d2(0);
  let proceeds = d2(0);
  let levelsUsed = 0;
  let depth = d2(0);
  for (const lvl of levels) {
    depth = depth.plus(lvl.price.mul(lvl.qty));
    if (remaining.lte(0)) continue;
    const takeQty = Decimal2.min(remaining, lvl.qty);
    const takeNotional = takeQty.mul(lvl.price);
    sold = sold.plus(takeQty);
    proceeds = proceeds.plus(takeNotional);
    remaining = remaining.minus(takeQty);
    levelsUsed += 1;
  }
  const fullyFillable = remaining.lte(0) || remaining.div(assetQty).lt(1e-4);
  const avg = sold.gt(0) ? proceeds.div(sold) : null;
  const slip = avg && bestBid.gt(0) ? bestBid.minus(avg).div(bestBid).mul(100) : null;
  return {
    fullyFillable,
    quoteReceivedUsd: toNum(proceeds.toDecimalPlaces(8)),
    assetSold: toNum(sold.toDecimalPlaces(12)),
    averageExecutionPrice: avg ? toNum(avg.toDecimalPlaces(12)) : null,
    bestBid: toNum(bestBid),
    estimatedSlippagePct: slip ? toNum(slip.toDecimalPlaces(6)) : null,
    availableDepthUsd: toNum(depth.toDecimalPlaces(2)),
    unsoldAssetQty: toNum(Decimal2.max(0, remaining).toDecimalPlaces(12)),
    levelsUsed
  };
}

// src/route-validator/transfer.ts
var ESTIMATED_WITHDRAWAL_FEES = [
  {
    asset: "BTC",
    exchange: "Binance",
    network: "BTC",
    feeAsset: 2e-4,
    sourceNote: "Estimated on-chain BTC withdrawal fee (not live).",
    lastVerified: "2026-08-06",
    sourceUrl: "https://www.binance.com/en/fee/cryptoFee"
  },
  {
    asset: "ETH",
    exchange: "Binance",
    network: "ETH",
    feeAsset: 15e-4,
    sourceNote: "Estimated ETH network withdrawal fee (not live).",
    lastVerified: "2026-08-06",
    sourceUrl: "https://www.binance.com/en/fee/cryptoFee"
  },
  {
    asset: "SOL",
    exchange: "Binance",
    network: "SOL",
    feeAsset: 0.01,
    sourceNote: "Estimated SOL withdrawal fee (not live).",
    lastVerified: "2026-08-06",
    sourceUrl: "https://www.binance.com/en/fee/cryptoFee"
  },
  {
    asset: "XRP",
    exchange: "Binance",
    network: "XRP",
    feeAsset: 0.25,
    sourceNote: "Estimated XRP withdrawal fee (not live).",
    lastVerified: "2026-08-06",
    sourceUrl: "https://www.binance.com/en/fee/cryptoFee"
  }
];
function findEstimatedWithdrawal(exchange, asset, preferredNetwork) {
  const rows = ESTIMATED_WITHDRAWAL_FEES.filter(
    (r) => r.exchange === exchange && r.asset === asset
  );
  if (!rows.length) return null;
  if (preferredNetwork) {
    const match = rows.find(
      (r) => r.network.toUpperCase() === preferredNetwork.toUpperCase()
    );
    if (match) return match;
  }
  return rows[0] ?? null;
}
async function buildTransferRoute(opts) {
  const buyAdapter = getAdapter(opts.buyExchange);
  const sellAdapter = getAdapter(opts.sellExchange);
  let buyMeta = null;
  let sellMeta = null;
  try {
    buyMeta = await buyAdapter.fetchTransferMeta?.(opts.asset) ?? null;
  } catch {
    buyMeta = null;
  }
  try {
    sellMeta = await sellAdapter.fetchTransferMeta?.(opts.asset) ?? null;
  } catch {
    sellMeta = null;
  }
  if (!buyMeta || !sellMeta) {
    const estimated = findEstimatedWithdrawal(
      opts.buyExchange,
      opts.asset,
      opts.preferredNetwork
    );
    const override = opts.withdrawalFeeOverride != null && Number.isFinite(opts.withdrawalFeeOverride) ? opts.withdrawalFeeOverride : null;
    return {
      depositEnabled: null,
      withdrawalEnabled: null,
      // Common network only when both exchanges clearly support it (not from estimates).
      commonNetworks: [],
      selectedNetwork: opts.preferredNetwork ?? null,
      withdrawalFeeAsset: override,
      networkFeeAsset: opts.networkFeeOverride != null && Number.isFinite(opts.networkFeeOverride) ? opts.networkFeeOverride : null,
      minWithdrawalAsset: null,
      confirmations: null,
      sourceType: override != null ? "estimated" : "unavailable",
      lastVerified: estimated?.lastVerified ?? null,
      unavailableReason: "Public transfer metadata is not available for this exchange pair without private API keys.",
      note: override != null ? "Withdrawal fee provided by user override. Deposit/withdrawal status still unverified." : estimated ? `Live transfer status unavailable. Optional estimated fee for ${estimated.network} exists but is not applied unless you override.` : "Live transfer status and fees unavailable."
    };
  }
  const buyNets = new Set(buyMeta.networks.map((n) => n.network.toUpperCase()));
  const sellNets = sellMeta.networks.map((n) => n.network).filter((n) => buyNets.has(n.toUpperCase()));
  let selected = opts.preferredNetwork && sellNets.some((n) => n.toUpperCase() === opts.preferredNetwork.toUpperCase()) ? opts.preferredNetwork : sellNets[0] ?? null;
  const buyRow = buyMeta.networks.find(
    (n) => selected && n.network.toUpperCase() === selected.toUpperCase()
  );
  const sellRow = sellMeta.networks.find(
    (n) => selected && n.network.toUpperCase() === selected.toUpperCase()
  );
  const withdrawalFee = opts.withdrawalFeeOverride != null && Number.isFinite(opts.withdrawalFeeOverride) ? opts.withdrawalFeeOverride : buyRow?.withdrawFee ?? null;
  return {
    depositEnabled: sellRow?.depositEnable ?? null,
    withdrawalEnabled: buyRow?.withdrawEnable ?? null,
    commonNetworks: sellNets,
    selectedNetwork: selected,
    withdrawalFeeAsset: withdrawalFee,
    networkFeeAsset: opts.networkFeeOverride != null && Number.isFinite(opts.networkFeeOverride) ? opts.networkFeeOverride : null,
    minWithdrawalAsset: buyRow?.minWithdraw ?? null,
    confirmations: buyRow?.confirmations ?? null,
    sourceType: "live",
    lastVerified: buyMeta.fetchedAt,
    unavailableReason: sellNets.length ? null : "No common network found.",
    note: null
  };
}

// src/route-validator/validate.ts
function optNum(raw) {
  if (raw === null || raw === void 0 || raw === "") return null;
  const n = typeof raw === "number" ? raw : Number(raw);
  return Number.isFinite(n) ? n : Number.NaN;
}
function validateRouteRequest(raw) {
  if (!raw || typeof raw !== "object") return { ok: false, reason: "invalid_payload" };
  const body = raw;
  const assetRaw = normalizeValidatorAsset(body.asset);
  if (assetRaw === "USDT") return { ok: false, reason: "usdt_asset_unsupported" };
  if (!assetRaw) return { ok: false, reason: "unsupported_asset" };
  const quote = typeof body.quote === "string" ? body.quote.trim().toUpperCase() : "USDT";
  if (quote !== "USDT") return { ok: false, reason: "unsupported_quote" };
  const buy = normalizeValidatorExchange(body.buy_exchange);
  const sell = normalizeValidatorExchange(body.sell_exchange);
  if (!buy || !sell) return { ok: false, reason: "unsupported_exchange" };
  if (buy === sell) return { ok: false, reason: "same_exchange" };
  const amount = optNum(body.trade_amount_usd);
  if (amount === null || Number.isNaN(amount) || amount < MIN_TRADE_USD || amount > MAX_TRADE_USD) {
    return { ok: false, reason: "invalid_amount" };
  }
  const overridesRaw = body.overrides && typeof body.overrides === "object" ? body.overrides : {};
  const buyFee = optNum(overridesRaw.buy_fee_pct);
  const sellFee = optNum(overridesRaw.sell_fee_pct);
  const wd = optNum(overridesRaw.withdrawal_fee_asset);
  const net = optNum(overridesRaw.network_fee_asset);
  for (const n of [buyFee, sellFee, wd, net]) {
    if (Number.isNaN(n) || n != null && n < 0) return { ok: false, reason: "invalid_override" };
  }
  if (buyFee != null && buyFee > 5) return { ok: false, reason: "invalid_override" };
  if (sellFee != null && sellFee > 5) return { ok: false, reason: "invalid_override" };
  const preferred = typeof body.preferred_network === "string" && body.preferred_network.trim() ? body.preferred_network.trim().slice(0, 32) : null;
  return {
    ok: true,
    value: {
      asset: assetRaw,
      quote: "USDT",
      buy_exchange: buy,
      sell_exchange: sell,
      trade_amount_usd: amount,
      preferred_network: preferred,
      overrides: {
        buy_fee_pct: buyFee,
        sell_fee_pct: sellFee,
        withdrawal_fee_asset: wd,
        network_fee_asset: net
      }
    }
  };
}

// src/route-validator/verdict.ts
var SAFETY_PROFIT_USD = 1;
var SAFETY_PROFIT_PCT = 0.05;
var FRESH_SEC = 12;
function computeVerdict(input) {
  const warnings = [...[]];
  if (input.bookStale) {
    return {
      verdict: "stale_data",
      confidence: "low",
      warnings: ["Order-book data may be stale. Recheck before relying on this result."]
    };
  }
  if (!input.buy.fullyFillable || !input.sell.fullyFillable) {
    return {
      verdict: "insufficient_liquidity",
      confidence: "medium",
      warnings: [
        !input.buy.fullyFillable ? "Buy side could not fully fill the requested amount from the live order book." : "Sell side could not fully fill the transferable quantity from the live order book."
      ]
    };
  }
  if (input.transfer.withdrawalEnabled === false || input.transfer.depositEnabled === false) {
    return {
      verdict: "transfer_unavailable",
      confidence: "high",
      warnings: ["Deposit or withdrawal is reported disabled for the selected network."]
    };
  }
  const transferVerified = input.transferLiveVerified && input.transfer.selectedNetwork != null && input.transfer.commonNetworks.length > 0 && input.transfer.depositEnabled === true && input.transfer.withdrawalEnabled === true && input.withdrawalFeeKnown;
  if (!transferVerified) {
    warnings.push(
      input.transfer.unavailableReason || "Transfer route is not fully verified from live public exchange data."
    );
    if (!input.withdrawalFeeKnown) {
      warnings.push(
        "Withdrawal fee is unavailable. Provide a user override to improve cost accuracy. Missing fees are not treated as zero."
      );
    }
    if (input.netProfitUsd == null) {
      return { verdict: "transfer_unverified", confidence: "low", warnings };
    }
    if (input.netProfitUsd <= 0) {
      return {
        verdict: "not_profitable",
        confidence: "medium",
        warnings
      };
    }
    return {
      verdict: "transfer_unverified",
      confidence: input.freshnessSeconds <= FRESH_SEC ? "medium" : "low",
      warnings
    };
  }
  if (input.netProfitUsd == null) {
    return { verdict: "unavailable", confidence: "low", warnings: ["Net profit could not be computed."] };
  }
  if (input.netProfitUsd <= 0) {
    return {
      verdict: "not_profitable",
      confidence: "high",
      warnings: ["Estimated net result is not positive after modeled costs."]
    };
  }
  if (input.netProfitUsd < SAFETY_PROFIT_USD || input.netProfitPct != null && input.netProfitPct < SAFETY_PROFIT_PCT) {
    return {
      verdict: "marginal",
      confidence: "medium",
      warnings: ["Estimated net profit is positive but below the safety threshold."]
    };
  }
  return {
    verdict: "potentially_executable",
    confidence: "high",
    warnings: [
      "Potentially executable based on current public data. Conditions can change before you finish transferring and trading."
    ]
  };
}

// src/route-validator/service.ts
function sideFromBuy(exchange, symbol, bookTs, sim) {
  return {
    exchange,
    symbol,
    bestPrice: sim.bestAsk,
    averageExecutionPrice: sim.averageExecutionPrice,
    estimatedSlippagePct: sim.estimatedSlippagePct,
    quoteSpentOrReceivedUsd: sim.quoteSpentUsd,
    assetQuantity: sim.assetQuantity,
    availableDepthUsd: sim.availableDepthUsd,
    fullyFillable: sim.fullyFillable,
    unfilledQuoteUsd: sim.unfilledQuoteUsd,
    unsoldAssetQty: 0,
    levelsUsed: sim.levelsUsed,
    orderBookTimestampMs: bookTs,
    sourceType: "live"
  };
}
function sideFromSell(exchange, symbol, bookTs, sim) {
  return {
    exchange,
    symbol,
    bestPrice: sim.bestBid,
    averageExecutionPrice: sim.averageExecutionPrice,
    estimatedSlippagePct: sim.estimatedSlippagePct,
    quoteSpentOrReceivedUsd: sim.quoteReceivedUsd,
    assetQuantity: sim.assetSold,
    availableDepthUsd: sim.availableDepthUsd,
    fullyFillable: sim.fullyFillable,
    unfilledQuoteUsd: 0,
    unsoldAssetQty: sim.unsoldAssetQty,
    levelsUsed: sim.levelsUsed,
    orderBookTimestampMs: bookTs,
    sourceType: "live"
  };
}
async function validateLiveRoute(raw, opts = {}) {
  const validated = validateRouteRequest(raw);
  if (!validated.ok) {
    const unsupported = validated.reason === "unsupported_asset" || validated.reason === "unsupported_exchange" || validated.reason === "unsupported_quote" || validated.reason === "usdt_asset_unsupported" || validated.reason === "same_exchange";
    return {
      ok: false,
      category: unsupported ? "unsupported" : "validation",
      reason: validated.reason
    };
  }
  const req = validated.value;
  const cacheKey = JSON.stringify({
    a: req.asset,
    b: req.buy_exchange,
    s: req.sell_exchange,
    amt: req.trade_amount_usd,
    n: req.preferred_network,
    o: req.overrides
  });
  if (!opts.skipCache) {
    const cached = cacheGet(cacheKey);
    if (cached) return { ok: true, result: cached, cacheHit: true };
  }
  const buySymbol = resolveSymbol(req.buy_exchange, req.asset);
  const sellSymbol = resolveSymbol(req.sell_exchange, req.asset);
  const now = (opts.now ?? (() => /* @__PURE__ */ new Date()))();
  let buyBook;
  let sellBook;
  try {
    const buyAdapter = getAdapter(req.buy_exchange);
    const sellAdapter = getAdapter(req.sell_exchange);
    [buyBook, sellBook] = await Promise.all([
      buyAdapter.fetchOrderBook(buySymbol),
      sellAdapter.fetchOrderBook(sellSymbol)
    ]);
  } catch (err) {
    const category = err instanceof UpstreamError && err.category === "timeout" ? "market_unavailable" : "market_unavailable";
    return { ok: false, category, reason: "upstream_failed" };
  }
  let buySim;
  let sellSim;
  try {
    buySim = simulateBuyFromAsks(buyBook.asks, req.trade_amount_usd);
    if (buySim.assetQuantity <= 0) {
      return { ok: false, category: "market_unavailable", reason: "zero_quantity" };
    }
  } catch {
    return { ok: false, category: "market_unavailable", reason: "book_simulation_failed" };
  }
  const transfer = await buildTransferRoute({
    asset: req.asset,
    buyExchange: req.buy_exchange,
    sellExchange: req.sell_exchange,
    preferredNetwork: req.preferred_network,
    withdrawalFeeOverride: req.overrides.withdrawal_fee_asset,
    networkFeeOverride: req.overrides.network_fee_asset
  });
  const withdrawalFeeKnown = transfer.withdrawalFeeAsset != null && Number.isFinite(transfer.withdrawalFeeAsset);
  const withdrawalFeeAsset = withdrawalFeeKnown ? Number(transfer.withdrawalFeeAsset) : 0;
  const networkFeeAsset = transfer.networkFeeAsset != null && Number.isFinite(transfer.networkFeeAsset) ? Number(transfer.networkFeeAsset) : 0;
  const sellQtyForBook = Math.max(
    0,
    buySim.assetQuantity - (withdrawalFeeKnown ? withdrawalFeeAsset : 0) - networkFeeAsset
  );
  try {
    if (sellQtyForBook <= 0) {
      sellSim = {
        fullyFillable: false,
        quoteReceivedUsd: 0,
        assetSold: 0,
        averageExecutionPrice: null,
        bestBid: null,
        estimatedSlippagePct: null,
        availableDepthUsd: 0,
        unsoldAssetQty: buySim.assetQuantity,
        levelsUsed: 0
      };
    } else {
      sellSim = simulateSellFromBids(sellBook.bids, sellQtyForBook);
    }
  } catch {
    return { ok: false, category: "market_unavailable", reason: "sell_simulation_failed" };
  }
  const buyFeeEst = getEstimatedTakerFeePct(req.buy_exchange);
  const sellFeeEst = getEstimatedTakerFeePct(req.sell_exchange);
  const buyFee = req.overrides.buy_fee_pct != null ? req.overrides.buy_fee_pct : buyFeeEst;
  const sellFee = req.overrides.sell_fee_pct != null ? req.overrides.sell_fee_pct : sellFeeEst;
  const unavailable = [];
  if (!withdrawalFeeKnown) unavailable.push("withdrawal_fee_asset");
  if (transfer.depositEnabled == null) unavailable.push("deposit_status");
  if (transfer.withdrawalEnabled == null) unavailable.push("withdrawal_status");
  if (!transfer.selectedNetwork) unavailable.push("common_network");
  if (transfer.networkFeeAsset == null && req.overrides.network_fee_asset == null) {
    unavailable.push("network_fee_asset");
  }
  let netProfit = null;
  if (buySim.averageExecutionPrice != null && sellSim.averageExecutionPrice != null && buyFee != null && sellFee != null && buySim.assetQuantity > 0) {
    netProfit = calculateNetProfit({
      investmentUsd: req.trade_amount_usd,
      buyExchange: req.buy_exchange,
      sellExchange: req.sell_exchange,
      assetSymbol: req.asset,
      buyPrice: buySim.averageExecutionPrice,
      sellPrice: sellSim.averageExecutionPrice,
      buyTradingFeePct: buyFee,
      sellTradingFeePct: sellFee,
      withdrawalFeeAsset: withdrawalFeeKnown ? withdrawalFeeAsset : 0,
      networkFeeAsset,
      buySlippagePct: 0,
      sellSlippagePct: 0,
      additionalCostUsd: 0
    });
  }
  const buySide = sideFromBuy(req.buy_exchange, buySymbol, buyBook.exchangeTimestampMs, buySim);
  const sellSide = sideFromSell(req.sell_exchange, sellSymbol, sellBook.exchangeTimestampMs, sellSim);
  const freshestMs = Math.max(
    Date.parse(buyBook.fetchedAt) || 0,
    Date.parse(sellBook.fetchedAt) || 0
  );
  const freshnessSeconds = Math.max(0, Math.round((now.getTime() - freshestMs) / 1e3));
  const bookStale = buyBook.exchangeTimestampMs != null && now.getTime() - buyBook.exchangeTimestampMs > STALE_BOOK_MS || sellBook.exchangeTimestampMs != null && now.getTime() - sellBook.exchangeTimestampMs > STALE_BOOK_MS;
  const transferLiveVerified = transfer.sourceType === "live";
  const verdictOut = computeVerdict({
    buy: buySide,
    sell: sellSide,
    transfer,
    netProfitUsd: netProfit ? netProfit.estimatedNetProfitUsd : null,
    netProfitPct: netProfit ? netProfit.netProfitPct : null,
    freshnessSeconds,
    bookStale,
    withdrawalFeeKnown,
    transferLiveVerified
  });
  const dataSources = [
    {
      exchange: req.buy_exchange,
      category: "order_book",
      kind: "live",
      fetchedAt: buyBook.fetchedAt,
      stale: bookStale,
      note: "Public spot order book"
    },
    {
      exchange: req.sell_exchange,
      category: "order_book",
      kind: "live",
      fetchedAt: sellBook.fetchedAt,
      stale: bookStale,
      note: "Public spot order book"
    },
    {
      exchange: req.buy_exchange,
      category: "transfer",
      kind: transfer.sourceType,
      fetchedAt: transfer.lastVerified,
      stale: false,
      ...transfer.note || transfer.unavailableReason ? { note: transfer.note ?? transfer.unavailableReason ?? "" } : {}
    },
    {
      exchange: req.buy_exchange,
      category: "fee_estimate",
      kind: "estimated",
      fetchedAt: null,
      stale: false,
      note: req.overrides.buy_fee_pct != null ? "User-provided value" : "VIP0-style estimated taker fee"
    },
    {
      exchange: req.sell_exchange,
      category: "fee_estimate",
      kind: "estimated",
      fetchedAt: null,
      stale: false,
      note: req.overrides.sell_fee_pct != null ? "User-provided value" : "VIP0-style estimated taker fee"
    }
  ];
  const expires = new Date(now.getTime() + RESULT_TTL_SECONDS * 1e3);
  const result = {
    request: {
      asset: req.asset,
      quote: "USDT",
      buy_exchange: req.buy_exchange,
      sell_exchange: req.sell_exchange,
      trade_amount_usd: req.trade_amount_usd,
      preferred_network: req.preferred_network
    },
    fetched_at: now.toISOString(),
    expires_at: expires.toISOString(),
    freshness_seconds: freshnessSeconds,
    buy_market: buySide,
    sell_market: sellSide,
    transfer_route: transfer,
    net_profit: {
      estimatedNetProfitUsd: netProfit ? netProfit.estimatedNetProfitUsd : null,
      netProfitPct: netProfit ? netProfit.netProfitPct : null,
      grossSpreadPct: netProfit ? netProfit.grossSpreadPct : null,
      breakEvenSpreadPct: netProfit ? netProfit.breakEvenSpreadPct : null,
      buyTradingFeeUsd: netProfit ? netProfit.buyTradingFeeUsd : null,
      sellTradingFeeUsd: netProfit ? netProfit.sellTradingFeeUsd : null,
      withdrawalCostUsd: netProfit && withdrawalFeeKnown ? netProfit.withdrawalCostUsd : null,
      engineVerdict: netProfit ? netProfit.verdict : null
    },
    fee_sources: {
      buy_fee_pct: buyFee,
      sell_fee_pct: sellFee,
      buy_fee_kind: req.overrides.buy_fee_pct != null ? "estimated" : "estimated",
      sell_fee_kind: req.overrides.sell_fee_pct != null ? "estimated" : "estimated",
      withdrawal_fee_kind: withdrawalFeeKnown ? req.overrides.withdrawal_fee_asset != null ? "estimated" : transfer.sourceType : "unavailable"
    },
    verdict: verdictOut.verdict,
    confidence: verdictOut.confidence,
    warnings: [...verdictOut.warnings, ...netProfit?.warnings ?? []],
    unavailable_fields: unavailable,
    data_sources: dataSources
  };
  cacheSet(cacheKey, result, RESULT_TTL_SECONDS * 1e3);
  return { ok: true, result, cacheHit: false };
}

// src/route-validator/http.ts
var MAX_BODY_BYTES = 8 * 1024;
function header(req, name) {
  const raw = req.headers?.[name] ?? req.headers?.[name.toLowerCase()];
  if (Array.isArray(raw)) return raw[0] || "";
  return typeof raw === "string" ? raw : "";
}
function clientIp(req) {
  const fwd = header(req, "x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim().slice(0, 64);
  return (req.socket?.remoteAddress || "unknown").slice(0, 64);
}
function readBody(req) {
  if (req.body == null) {
    return {
      ok: false,
      status: 400,
      response: {
        ok: false,
        error: { code: "VALIDATION_ERROR", message: "Please check the selected route and amount." }
      }
    };
  }
  if (typeof req.body === "string") {
    if (req.body.length > MAX_BODY_BYTES) {
      return {
        ok: false,
        status: 413,
        response: {
          ok: false,
          error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the selected route and amount." }
        }
      };
    }
    try {
      return { ok: true, value: JSON.parse(req.body) };
    } catch {
      return {
        ok: false,
        status: 400,
        response: {
          ok: false,
          error: { code: "VALIDATION_ERROR", message: "Please check the selected route and amount." }
        }
      };
    }
  }
  const encoded = JSON.stringify(req.body);
  if (encoded.length > MAX_BODY_BYTES) {
    return {
      ok: false,
      status: 413,
      response: {
        ok: false,
        error: { code: "PAYLOAD_TOO_LARGE", message: "Please check the selected route and amount." }
      }
    };
  }
  return { ok: true, value: req.body };
}
async function handleRouteValidatorRequest(req, res) {
  res.setHeader("Cache-Control", "no-store");
  res.setHeader("X-Robots-Tag", "noindex, nofollow");
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  if (req.method === "OPTIONS") {
    res.setHeader("Allow", "POST, OPTIONS");
    res.status(204).end();
    return;
  }
  if (req.method !== "POST") {
    res.status(405).json({
      ok: false,
      error: { code: "METHOD_NOT_ALLOWED", message: "Please check the selected route and amount." }
    });
    return;
  }
  const contentType = header(req, "content-type").toLowerCase();
  if (!contentType.includes("application/json")) {
    res.status(415).json({
      ok: false,
      error: { code: "VALIDATION_ERROR", message: "Please check the selected route and amount." }
    });
    return;
  }
  const ip = clientIp(req);
  const rl = checkRateLimit(`route-validator:${ip}`, 20, 6e4);
  if (!rl.allowed) {
    res.setHeader("Retry-After", String(rl.retryAfterSec));
    res.status(429).json({
      ok: false,
      error: { code: "RATE_LIMITED", message: "Too many requests. Please try again later." }
    });
    return;
  }
  const body = readBody(req);
  if (!body.ok) {
    res.status(body.status).json(body.response);
    return;
  }
  try {
    const outcome = await validateLiveRoute(body.value);
    if (!outcome.ok) {
      if (outcome.category === "validation") {
        res.status(400).json({
          ok: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Please check the selected route and amount."
          }
        });
        return;
      }
      if (outcome.category === "unsupported") {
        res.status(400).json({
          ok: false,
          error: {
            code: "VALIDATION_ERROR",
            message: "Please check the selected route and amount."
          }
        });
        return;
      }
      res.status(503).json({
        ok: false,
        error: {
          code: "MARKET_DATA_UNAVAILABLE",
          message: "Live market data is temporarily unavailable."
        }
      });
      return;
    }
    res.status(200).json({ ok: true, result: outcome.result });
  } catch {
    res.status(500).json({
      ok: false,
      error: {
        code: "SERVER_ERROR",
        message: "Live market data is temporarily unavailable."
      }
    });
  }
}

// src/route-validator/vercel/index.ts
async function handler(req, res) {
  await handleRouteValidatorRequest(req, res);
}
export {
  handler as default
};
